"""A plain country list for the 'Country of Birth' select — the existing architecture's `select` question kind
(a native HTML `<select>`, already used for MVC locations/US states) is inherently type-to-jump searchable on
both desktop and mobile; no new autocomplete widget exists anywhere else in this app, so this reuses that same
pattern rather than introducing one. `bind="birth_country"` (the canonical fact key already used by I-485/I-765/
I-130/N-400/DS-260 — see `case_types.py`) means an existing Person's country of birth is read/prefilled and
reused automatically by the SAME generic bound-field mechanism every other intake already relies on."""

COUNTRIES = [
    ("Afghanistan", "Afganistán"), ("Albania", "Albania"), ("Algeria", "Argelia"), ("Andorra", "Andorra"), ("Angola", "Angola"),
    ("Argentina", "Argentina"), ("Armenia", "Armenia"), ("Australia", "Australia"), ("Austria", "Austria"), ("Azerbaijan", "Azerbaiyán"),
    ("Bahamas", "Bahamas"), ("Bahrain", "Baréin"), ("Bangladesh", "Bangladés"), ("Barbados", "Barbados"), ("Belarus", "Bielorrusia"),
    ("Belgium", "Bélgica"), ("Belize", "Belice"), ("Benin", "Benín"), ("Bhutan", "Bután"), ("Bolivia", "Bolivia"),
    ("Bosnia and Herzegovina", "Bosnia y Herzegovina"), ("Botswana", "Botsuana"), ("Brazil", "Brasil"), ("Bulgaria", "Bulgaria"),
    ("Burkina Faso", "Burkina Faso"), ("Burundi", "Burundi"), ("Cambodia", "Camboya"), ("Cameroon", "Camerún"), ("Canada", "Canadá"),
    ("Cape Verde", "Cabo Verde"), ("Chad", "Chad"), ("Chile", "Chile"), ("China", "China"), ("Colombia", "Colombia"),
    ("Comoros", "Comoras"), ("Congo", "Congo"), ("Costa Rica", "Costa Rica"), ("Croatia", "Croacia"), ("Cuba", "Cuba"),
    ("Cyprus", "Chipre"), ("Czech Republic", "República Checa"), ("Democratic Republic of the Congo", "República Democrática del Congo"),
    ("Denmark", "Dinamarca"), ("Djibouti", "Yibuti"), ("Dominica", "Dominica"), ("Dominican Republic", "República Dominicana"),
    ("Ecuador", "Ecuador"), ("Egypt", "Egipto"), ("El Salvador", "El Salvador"), ("Equatorial Guinea", "Guinea Ecuatorial"),
    ("Eritrea", "Eritrea"), ("Estonia", "Estonia"), ("Eswatini", "Esuatini"), ("Ethiopia", "Etiopía"), ("Fiji", "Fiyi"),
    ("Finland", "Finlandia"), ("France", "Francia"), ("Gabon", "Gabón"), ("Gambia", "Gambia"), ("Georgia", "Georgia"),
    ("Germany", "Alemania"), ("Ghana", "Ghana"), ("Greece", "Grecia"), ("Grenada", "Granada"), ("Guatemala", "Guatemala"),
    ("Guinea", "Guinea"), ("Guinea-Bissau", "Guinea-Bisáu"), ("Guyana", "Guyana"), ("Haiti", "Haití"), ("Honduras", "Honduras"),
    ("Hong Kong", "Hong Kong"), ("Hungary", "Hungría"), ("Iceland", "Islandia"), ("India", "India"), ("Indonesia", "Indonesia"),
    ("Iran", "Irán"), ("Iraq", "Irak"), ("Ireland", "Irlanda"), ("Israel", "Israel"), ("Italy", "Italia"),
    ("Ivory Coast", "Costa de Marfil"), ("Jamaica", "Jamaica"), ("Japan", "Japón"), ("Jordan", "Jordania"), ("Kazakhstan", "Kazajistán"),
    ("Kenya", "Kenia"), ("Kiribati", "Kiribati"), ("Kosovo", "Kosovo"), ("Kuwait", "Kuwait"), ("Kyrgyzstan", "Kirguistán"),
    ("Laos", "Laos"), ("Latvia", "Letonia"), ("Lebanon", "Líbano"), ("Lesotho", "Lesoto"), ("Liberia", "Liberia"),
    ("Libya", "Libia"), ("Liechtenstein", "Liechtenstein"), ("Lithuania", "Lituania"), ("Luxembourg", "Luxemburgo"),
    ("Madagascar", "Madagascar"), ("Malawi", "Malaui"), ("Malaysia", "Malasia"), ("Maldives", "Maldivas"), ("Mali", "Malí"),
    ("Malta", "Malta"), ("Marshall Islands", "Islas Marshall"), ("Mauritania", "Mauritania"), ("Mauritius", "Mauricio"),
    ("Mexico", "México"), ("Micronesia", "Micronesia"), ("Moldova", "Moldavia"), ("Monaco", "Mónaco"), ("Mongolia", "Mongolia"),
    ("Montenegro", "Montenegro"), ("Morocco", "Marruecos"), ("Mozambique", "Mozambique"), ("Myanmar (Burma)", "Myanmar (Birmania)"),
    ("Namibia", "Namibia"), ("Nauru", "Nauru"), ("Nepal", "Nepal"), ("Netherlands", "Países Bajos"), ("New Zealand", "Nueva Zelanda"),
    ("Nicaragua", "Nicaragua"), ("Niger", "Níger"), ("Nigeria", "Nigeria"), ("North Korea", "Corea del Norte"),
    ("North Macedonia", "Macedonia del Norte"), ("Norway", "Noruega"), ("Oman", "Omán"), ("Pakistan", "Pakistán"), ("Palau", "Palaos"),
    ("Palestine", "Palestina"), ("Panama", "Panamá"), ("Papua New Guinea", "Papúa Nueva Guinea"), ("Paraguay", "Paraguay"),
    ("Peru", "Perú"), ("Philippines", "Filipinas"), ("Poland", "Polonia"), ("Portugal", "Portugal"), ("Qatar", "Catar"),
    ("Romania", "Rumania"), ("Russia", "Rusia"), ("Rwanda", "Ruanda"), ("Saint Kitts and Nevis", "San Cristóbal y Nieves"),
    ("Saint Lucia", "Santa Lucía"), ("Saint Vincent and the Grenadines", "San Vicente y las Granadinas"), ("Samoa", "Samoa"),
    ("San Marino", "San Marino"), ("Sao Tome and Principe", "Santo Tomé y Príncipe"), ("Saudi Arabia", "Arabia Saudita"),
    ("Senegal", "Senegal"), ("Serbia", "Serbia"), ("Seychelles", "Seychelles"), ("Sierra Leone", "Sierra Leona"),
    ("Singapore", "Singapur"), ("Slovakia", "Eslovaquia"), ("Slovenia", "Eslovenia"), ("Solomon Islands", "Islas Salomón"),
    ("Somalia", "Somalia"), ("South Africa", "Sudáfrica"), ("South Korea", "Corea del Sur"), ("South Sudan", "Sudán del Sur"),
    ("Spain", "España"), ("Sri Lanka", "Sri Lanka"), ("Sudan", "Sudán"), ("Suriname", "Surinam"), ("Sweden", "Suecia"),
    ("Switzerland", "Suiza"), ("Syria", "Siria"), ("Taiwan", "Taiwán"), ("Tajikistan", "Tayikistán"), ("Tanzania", "Tanzania"),
    ("Thailand", "Tailandia"), ("Timor-Leste", "Timor Oriental"), ("Togo", "Togo"), ("Tonga", "Tonga"),
    ("Trinidad and Tobago", "Trinidad y Tobago"), ("Tunisia", "Túnez"), ("Turkey", "Turquía"), ("Turkmenistan", "Turkmenistán"),
    ("Tuvalu", "Tuvalu"), ("Uganda", "Uganda"), ("Ukraine", "Ucrania"), ("United Arab Emirates", "Emiratos Árabes Unidos"),
    ("United Kingdom", "Reino Unido"), ("United States", "Estados Unidos"), ("Uruguay", "Uruguay"), ("Uzbekistan", "Uzbekistán"),
    ("Vanuatu", "Vanuatu"), ("Vatican City", "Ciudad del Vaticano"), ("Venezuela", "Venezuela"), ("Vietnam", "Vietnam"),
    ("Yemen", "Yemen"), ("Zambia", "Zambia"), ("Zimbabwe", "Zimbabue"), ("Other / not listed", "Otro / no listado"),
]
