"""Verbatim texts of USCIS Form I-751 (Petition to Remove Conditions on Residence), Edition 04/01/24, and OG's courtesy Spanish translations.

The English is the official text exactly as printed on the supplied PDF. The Spanish is OG's courtesy translation only (not USCIS text); the English
prevails. Nothing here is collected as a signature: the customer only reads these texts, and where a checkbox exists it is a reading acknowledgment.
"""

COURTESY = "OFFICIAL TEXT = the English as printed on Form I-751 edition 04/01/24. The Spanish is OG's courtesy translation only (not USCIS text); the English prevails."
COURTESY_NOTE_ES = "Abajo aparece una traducción de cortesía hecha por OG; no es un texto oficial de USCIS. El texto oficial es el del formulario en inglés y es el que prevalece."
COURTESY_SHORT_ES = "(Traducción de cortesía de OG; el texto oficial es el inglés.)"

# ------------------------------------------------------------------ Part 3 — basis for petition (Items 1.a-1.g)
JOINT_INTRO = ("My conditional residence is based on my marriage or my parent's marriage to a U.S. citizen or lawful permanent resident, and I am filing this joint petition together with (Select only one box):",
               "Mi residencia condicional se basa en mi matrimonio o en el matrimonio de mi padre o madre con un ciudadano de EE. UU. o residente permanente legal, y presento esta petición conjunta junto con (selecciona solo una casilla):")
JOINT_OPTIONS = [
    ("1a", "My spouse.", "Mi cónyuge."),
    ("1b", "My parent's spouse because I am unable to be included in a joint petition filed by my parent and my parent's spouse.",
     "El cónyuge de mi padre o madre, porque no puedo ser incluido(a) en una petición conjunta presentada por mi padre o madre y su cónyuge."),
]
WAIVER_INTRO = ("My conditional residence is based on my marriage or my parent's marriage to a U.S. citizen or lawful permanent resident, I am unable to file a joint petition with my spouse or my parent's spouse, because:",
                "Mi residencia condicional se basa en mi matrimonio o en el matrimonio de mi padre o madre con un ciudadano de EE. UU. o residente permanente legal, no puedo presentar una petición conjunta con mi cónyuge o con el cónyuge de mi padre o madre, porque:")
WAIVER_OPTIONS = [
    ("1c", "My spouse is deceased.", "Mi cónyuge falleció."),
    ("1d", "My marriage was entered in good faith, but the marriage was terminated through divorce or annulment.",
     "Mi matrimonio se celebró de buena fe, pero el matrimonio terminó por divorcio o anulación."),
    ("1e", "I entered the marriage in good faith, and, during the marriage, I was battered, or was the subject of extreme cruelty, by my U.S. citizen or lawful permanent resident spouse.",
     "Me casé de buena fe y, durante el matrimonio, fui maltratado(a) o fui objeto de crueldad extrema por parte de mi cónyuge ciudadano de EE. UU. o residente permanente legal."),
    ("1f", "My parent entered the marriage in good faith, and, during the marriage, I was battered, or was subjected to extreme cruelty, by my parent's U.S. citizen or lawful permanent resident spouse or by my conditional resident parent.",
     "Mi padre o madre se casó de buena fe y, durante el matrimonio, fui maltratado(a) o sometido(a) a crueldad extrema por parte del cónyuge ciudadano de EE. UU. o residente permanente legal de mi padre o madre, o por mi padre o madre residente condicional."),
    ("1g", "The termination of my status and removal from the United States would result in an extreme hardship.",
     "La terminación de mi estatus y mi expulsión de los Estados Unidos resultarían en una dificultad extrema."),
]

# ------------------------------------------------------------------ Part 7 — petitioner's statement, ASC acknowledgement, certification
P7_NOTE_EN = "NOTE: If you selected Box 1.a in Part 3., your spouse must also read and sign the petition in Part 8. Signature of a conditional resident child under 14 years of age is not required; a parent may sign for a child."
P7_NOTE_ES = "NOTA: Si seleccionaste la casilla 1.a de la Parte 3, tu cónyuge también debe leer y firmar la petición en la Parte 8. No se requiere la firma de un hijo(a) residente condicional menor de 14 años; un padre o madre puede firmar por el hijo(a)."
P7_STATEMENT_A_EN = "I can read and understand English, and have read and understand every question and instruction on this petition, as well as my answer to every question. I have read and understand the Acknowledgement of Appointment at USCIS Application Support Center."
P7_STATEMENT_A_ES = "Puedo leer y entender inglés, y he leído y entendido cada pregunta e instrucción de esta petición, así como mi respuesta a cada pregunta. He leído y entendido el Reconocimiento de la Cita en el Centro de Servicio de Solicitudes (ASC) de USCIS."
P7_STATEMENT_B_EN = "The interpreter named in Part 9. has also read to me every question and instruction on this petition, as well as my answer to every question, in {language}, a language in which I am fluent. I understand every question and instruction on this petition as translated to me by my interpreter, and have provided complete, true, and correct responses in the language indicated above. The interpreter named in Part 9. has also read the Acknowledgement of Appointment at USCIS Application Support Center to me, in the language in which I am fluent, and I understand this Application Support Center (ASC) Acknowledgement as read to me by my interpreter."
P7_STATEMENT_B_ES = "El intérprete nombrado en la Parte 9 también me leyó cada pregunta e instrucción de esta petición, así como mi respuesta a cada pregunta, en {language}, un idioma en el que soy fluido(a). Entiendo cada pregunta e instrucción de esta petición según me fue traducida por mi intérprete, y he dado respuestas completas, verdaderas y correctas en el idioma indicado arriba. El intérprete nombrado en la Parte 9 también me leyó el Reconocimiento de la Cita en el Centro de Servicio de Solicitudes de USCIS en el idioma en el que soy fluido(a), y entiendo este Reconocimiento del ASC tal como me lo leyó mi intérprete."
P7_PREPARER_EN = "I have requested the services of and consented to {name}, who {is_not} an attorney or accredited representative, preparing this petition for me. This person who assisted me in preparing my petition has reviewed the Acknowledgement of Appointment at USCIS Application Support Center with me, and I understand the ASC Acknowledgement."
P7_PREPARER_ES = "He solicitado los servicios de {name}, quien {is_not} abogado o representante acreditado, y he dado mi consentimiento para que prepare esta petición por mí. Esta persona que me ayudó a preparar mi petición ha revisado conmigo el Reconocimiento de la Cita en el Centro de Servicio de Solicitudes de USCIS, y entiendo el Reconocimiento del ASC."

ASC_EN = [
    "I, {name}, understand that the purpose of a USCIS ASC appointment is for me to provide fingerprints, photograph, and/or signature and to re-affirm that all of the information in my petition is complete, true, and correct and was provided by me. I understand that I will sign my name to the following declaration which USCIS will display to me at the time I provide my fingerprints, photograph, and/or signature during my ASC appointment.",
    "<strong>By signing here, I declare under penalty of perjury that I have reviewed and understand my application, petition, or request as identified by the receipt number displayed on the screen above, and all supporting documents, applications, petitions, or requests filed with my application, petition, or request that I (or my attorney or accredited representative) filed with USCIS, and that all of the information in these materials is complete, true, and correct.</strong>",
    "If conditional residence was based on a marriage, I further certify that the marriage was entered into in accordance with the laws of the place where the marriage took place and was not for the purpose of procuring an immigration benefit.",
    "I also understand that when I sign my name, provide my fingerprints, and am photographed at the USCIS ASC, I will be re-affirming that I willingly submit this petition; I have reviewed the contents of this petition; all of the information in my petition and all supporting documents submitted with my petition were provided by me and are complete, true, and correct; and if I was assisted in completing this petition, the person assisting me also reviewed this Acknowledgement of Appointment at USCIS Application Support Center with me.",
]
ASC_ES = [
    "Yo, {name}, entiendo que el propósito de una cita en el ASC de USCIS es que yo proporcione mis huellas digitales, fotografía y/o firma y que reafirme que toda la información de mi petición es completa, verdadera y correcta y fue proporcionada por mí. Entiendo que firmaré con mi nombre la siguiente declaración que USCIS me mostrará en el momento en que proporcione mis huellas digitales, fotografía y/o firma durante mi cita en el ASC.",
    "<strong>Al firmar aquí, declaro bajo pena de perjurio que he revisado y entiendo mi solicitud, petición o requerimiento según se identifica con el número de recibo que aparece en la pantalla de arriba, y todos los documentos de respaldo, solicitudes, peticiones o requerimientos presentados con mi solicitud, petición o requerimiento que yo (o mi abogado o representante acreditado) presenté ante USCIS, y que toda la información en estos materiales es completa, verdadera y correcta.</strong>",
    "Si la residencia condicional se basó en un matrimonio, certifico además que el matrimonio se celebró de acuerdo con las leyes del lugar donde se celebró y no fue con el propósito de obtener un beneficio migratorio.",
    "También entiendo que cuando firme con mi nombre, proporcione mis huellas digitales y sea fotografiado(a) en el ASC de USCIS, estaré reafirmando que presento esta petición voluntariamente; que he revisado el contenido de esta petición; que toda la información de mi petición y todos los documentos de respaldo presentados con mi petición fueron proporcionados por mí y son completos, verdaderos y correctos; y que, si recibí ayuda para completar esta petición, la persona que me ayudó también revisó conmigo este Reconocimiento de la Cita en el Centro de Servicio de Solicitudes de USCIS.",
]
CERT_EN = [
    "Copies of any documents I have submitted are exact photocopies of unaltered, original documents, and I understand that USCIS may require that I submit original documents to USCIS at a later date. Furthermore, I authorize the release of any information from any and all of my records that USCIS may need to determine my eligibility for the immigration benefit that I seek. I furthermore authorize release of information contained in this petition, in supporting documents, and in my USCIS records to other entities and persons where necessary for the administration and enforcement of U.S. immigration laws.",
    "I certify under penalty of perjury, that the information in my petition, my responses to each question, and any document submitted with my petition were provided by me and are complete, true, and correct.",
    "<strong>NOTE TO ALL PETITIONERS:</strong> If you do not completely fill out this petition or fail to submit required documents listed in the Instructions, USCIS may deny your petition.",
    "<strong>NOTE:</strong> If you are filing based on claims of having been battered or subjected to extreme cruelty waiver or individual filing, you are not required to have the spouse's or individual listed in Part 4's signature.",
]
CERT_ES = [
    "Las copias de cualquier documento que he presentado son fotocopias exactas de documentos originales sin alterar, y entiendo que USCIS puede exigir que presente documentos originales a USCIS en una fecha posterior. Además, autorizo la divulgación de cualquier información de todos mis registros que USCIS pueda necesitar para determinar mi elegibilidad para el beneficio migratorio que solicito. Asimismo, autorizo la divulgación de la información contenida en esta petición, en los documentos de respaldo y en mis registros de USCIS, a otras entidades y personas cuando sea necesario para la administración y aplicación de las leyes de inmigración de EE. UU.",
    "Certifico, bajo pena de perjurio, que la información de mi petición, mis respuestas a cada pregunta y cualquier documento presentado con mi petición fueron proporcionados por mí y son completos, verdaderos y correctos.",
    "<strong>NOTA PARA TODOS LOS PETICIONARIOS:</strong> Si no completas por completo esta petición o no presentas los documentos requeridos que se enumeran en las Instrucciones, USCIS puede denegar tu petición.",
    "<strong>NOTA:</strong> Si presentas con base en reclamos de haber sido maltratado(a) o sometido(a) a crueldad extrema, con dispensa o presentación individual, no se requiere que el cónyuge o la persona indicada en la Parte 4 firme.",
]

# ------------------------------------------------------------------ Part 8 — the Part 4 spouse's / individual's own statement
P8_INTRO_EN = "Provide the following information about the spouse or individual listed in Part 4."
P8_INTRO_ES = "Proporciona la siguiente información sobre el cónyuge o la persona indicada en la Parte 4."
P8_STATEMENT_A_EN = "I can read and understand English, and have read and understand every question and instruction on this petition, as well as the petitioner's answer to every question. I have read and understand the Acknowledgement of Appointment at USCIS Application Support Center."
P8_STATEMENT_A_ES = "Puedo leer y entender inglés, y he leído y entendido cada pregunta e instrucción de esta petición, así como la respuesta del peticionario a cada pregunta. He leído y entendido el Reconocimiento de la Cita en el Centro de Servicio de Solicitudes (ASC) de USCIS."
P8_STATEMENT_B_EN = "The interpreter named in Part 9. has also read to me every question and instruction on this petition, as well as the petitioner's answer to every question, in {language}, a language in which I am fluent. I understand every question and instruction on this petition as translated to me by my interpreter, and have provided complete, true, and correct responses in the language indicated above. The interpreter named in Part 9. has also read the Acknowledgement of Appointment at USCIS Application Support Center to me, in the language in which I am fluent, and I understand this Application Support Center (ASC) Acknowledgement as read to me by my interpreter."
P8_STATEMENT_B_ES = "El intérprete nombrado en la Parte 9 también me leyó cada pregunta e instrucción de esta petición, así como la respuesta del peticionario a cada pregunta, en {language}, un idioma en el que soy fluido(a). Entiendo cada pregunta e instrucción de esta petición según me fue traducida por mi intérprete, y he dado respuestas completas, verdaderas y correctas en el idioma indicado arriba. El intérprete nombrado en la Parte 9 también me leyó el Reconocimiento de la Cita en el Centro de Servicio de Solicitudes de USCIS en el idioma en el que soy fluido(a), y entiendo este Reconocimiento del ASC tal como me lo leyó mi intérprete."
P8_CERT_NOTE_EN = "<strong>NOTE TO ALL SPOUSES OR INDIVIDUALS:</strong> If you do not completely fill out this petition or fail to submit required documents listed in the instructions, USCIS may deny your petition."
P8_CERT_NOTE_ES = "<strong>NOTA PARA TODOS LOS CÓNYUGES O PERSONAS:</strong> Si no completas por completo esta petición o no presentas los documentos requeridos que se enumeran en las instrucciones, USCIS puede denegar tu petición."

# ------------------------------------------------------------------ Part 9 / Part 10
INTERP_CERT_EN = "I certify that: I am fluent in English and {language}, which is the same language provided in Part 7., Item Number 1.b.; I have read to this petitioner every question and instruction on this petition, as well as the answer to every question, in the language provided in Part 7., Item Number 1.b.; and I have read the Acknowledgement of Appointment at USCIS Application Support Center to the petitioner in the same language provided in Part 7., Item Number 1.b. The petitioner has informed me that he or she understands every instruction and question on the petition, as well as the answer to every question, and the petitioner verified the accuracy of every answer; and the petitioner has also informed me that he or she understands the ASC Acknowledgement and that by appearing for a USCIS ASC biometric services appointment and providing his or her fingerprints, photograph, and/or signature, he or she is re-affirming that the contents of this petition and all supporting documentation are complete, true, and correct."
INTERP_CERT_ES = "Certifico que: soy fluido(a) en inglés y en {language}, que es el mismo idioma indicado en la Parte 7, Ítem 1.b.; le he leído a este peticionario cada pregunta e instrucción de esta petición, así como la respuesta a cada pregunta, en el idioma indicado en la Parte 7, Ítem 1.b.; y le he leído el Reconocimiento de la Cita en el Centro de Servicio de Solicitudes de USCIS al peticionario en el mismo idioma indicado en la Parte 7, Ítem 1.b. El peticionario me informó que entiende cada instrucción y pregunta de la petición, así como la respuesta a cada pregunta, y el peticionario verificó la exactitud de cada respuesta; y el peticionario también me informó que entiende el Reconocimiento del ASC y que, al presentarse a una cita de servicios biométricos en el ASC de USCIS y proporcionar sus huellas digitales, fotografía y/o firma, reafirma que el contenido de esta petición y toda la documentación de respaldo son completos, verdaderos y correctos."
PREP_STATEMENT_EN = {
    "7.a": "I am not an attorney or accredited representative but have prepared this petition on behalf of the petitioner and with the petitioner's consent.",
    "7.b": "I am an attorney or accredited representative and my representation of the petitioner in this case {extends} beyond the preparation of this petition. NOTE: If you are an attorney or accredited representative whose representation extends beyond preparation of this petition, you must submit a completed Form G-28, Notice of Entry of Appearance as Attorney or Accredited Representative, with this petition.",
}
PREP_STATEMENT_ES = {
    "7.a": "No soy abogado ni representante acreditado, pero preparé esta petición en nombre del peticionario y con su consentimiento.",
    "7.b": "Soy abogado o representante acreditado y mi representación del peticionario en este caso {extends} más allá de la preparación de esta petición. NOTA: Si es abogado o representante acreditado cuya representación se extiende más allá de la preparación de esta petición, debe presentar con esta petición un Formulario G-28 completado, Notificación de Comparecencia como Abogado o Representante Acreditado.",
}
PREP_CERT_EN = "By my signature, I certify, swear, or affirm, under penalty of perjury, that I prepared this petition on behalf of, at the request of, and with the express consent of the petitioner. I completed this petition based only on responses the petitioner provided to me. After completing the petition, I reviewed it and all of the petitioner's responses with the petitioner, who agreed with every answer on the petition. If the petitioner supplied additional information concerning a question on the petition, I recorded it on the petition. I have also read the Acknowledgement of Appointment at USCIS Application Support Center to the petitioner and the petitioner has informed me that he or she understands the ASC Acknowledgement"
PREP_CERT_ES = "Con mi firma, certifico, juro o afirmo, bajo pena de perjurio, que preparé esta petición en nombre del peticionario, a petición suya y con su consentimiento expreso. Completé esta petición basándome únicamente en las respuestas que el peticionario me proporcionó. Después de completar la petición, la revisé junto con todas las respuestas del peticionario, quien estuvo de acuerdo con cada respuesta de la petición. Si el peticionario proporcionó información adicional sobre una pregunta de la petición, la registré en la petición. También le he leído al peticionario el Reconocimiento de la Cita en el Centro de Servicio de Solicitudes de USCIS y el peticionario me ha informado que entiende el Reconocimiento del ASC"

# ------------------------------------------------------------------ Part 6 — accommodations (wording as printed)
ACC_NOTE_EN = "NOTE: Read the information in the Form I-751 Instructions before completing this part."
ACC_NOTE_ES = "NOTA: Lee la información en las Instrucciones del Formulario I-751 antes de completar esta parte."
ACC_TYPES = [
    ("a", "I am deaf or hard of hearing and request the following accommodation. (If you are requesting a sign-language interpreter, indicate for which language (for example, American Sign Language).):",
     "Soy sordo(a) o tengo dificultades auditivas y solicito la siguiente adaptación. (Si solicitas un intérprete de lenguaje de señas, indica para qué idioma (por ejemplo, Lenguaje de Señas Americano).):"),
    ("b", "I am blind or have low vision and request the following accommodation:", "Soy ciego(a) o tengo baja visión y solicito la siguiente adaptación:"),
    ("c", "I have another type of disability and/or impairment. (Describe the nature of your disability and/or impairment and the accommodation you are requesting.):",
     "Tengo otro tipo de discapacidad y/o impedimento. (Describe la naturaleza de tu discapacidad y/o impedimento y la adaptación que solicitas.):"),
]
