"""Reference data transcribed from the supplied USCIS Form N-400 (edition 01/20/25).

OFFICES is the "select the USCIS field office" list from Part 1 (spelling kept exactly as printed on the form).
"""

OFFICES = [
    'Alaska - USCIS Anchorage Field Office',
    'Alabama - USCIS Montgomery Field Office',
    'Arkansas - USCIS Fort Smith Field Office',
    'Arizona - USCIS Phoenix Field Office',
    'Arizona - USCIS Tuscon Field Office',
    'California - USCIS Fresno Field Office',
    'California - USCIS Imperial Field Office',
    'California - USCIS Los Angeles County Field Offi',
    'California - USCIS Los Angeles Field Office',
    'California - USCIS Sacramento Field Office',
    'California - USCIS San Bernardino Field Office',
    'California - USCIS San Diego Field Office',
    'California - USCIS San Fernando Valley Field Office',
    'California - USCIS San Francisco Field Office',
    'California - USCIS San Jose Field Office',
    'California - USCIS Santa Ana Field Office',
    'California - USCIS Western Region Office',
    'Colorado - USCIS Denver Field Office',
    'Connecticut - USCIS Hartford Office',
    'Florida - USCIS Fort Myers Field Office',
    'Florida - USCIS Hialeah Field Office',
    'Florida - USCIS Jacksonville Field Office',
    'Florida - USCIS Kendall Field Office',
    'Florida - USCIS Miami Field Office',
    'Florida - USCIS Oakland Park Field Office',
    'Florida - USCIS Orlando Field Office',
    'Florida - USCIS Southeast Region Office',
    'Florida - USCIS Tampa Field Office',
    'Florida - USCIS West Palm Beach Field Office',
    'Georgia - USCIS Atlanta Field Office',
    'Guam - USCIS Guam Field Office',
    'Hawaii - USCIS Honolulu Field Office',
    'Iowa - USCIS Des Moines Field Office',
    'Idaho - USCIS Boise Field Office',
    'Illinois - USCIS Chicago Field Office',
    'Indiana - USCIS Indianapolis Field Office',
    'Kansas - USCIS National Benefits Center',
    'Kansas - USCIS Wichita Field Office',
    'Kentucky - USCIS Louisville Field Office',
    'Louisiana - USCIS New Orleans Field Office',
    'Massachusetts - USCIS Boston Field Office',
    'Massachusetts - USCIS Lawrence Field Office',
    'Maryland - USCIS Baltimore Field Office',
    'Maine - USCIS Portland Field Office',
    'Michigan - USCIS Detroit Field Office',
    'Minnesota - USCIS St Paul Field Office',
    'Missouri - USCIS Kansas City Field Office',
    'Missouri - USCIS National Benefits Center',
    'Missouri - USCIS St Louis Field Office',
    'Montana - USCIS Helena Field Office',
    'North Carolina - USCIS Charlotte Field Office',
    'North Carolina - USCIS Raleigh Field Office',
    'Nebraska - USCIS Omaha Field Office',
    'New Hampshire - USCIS Manchester Field Office',
    'New Jersey - USCIS Mount Laurel Field Office',
    'New Jersey - USCIS Newark Field Office',
    'New Mexico - USCIS Albuquerque Field Office',
    'Nevada - USCIS Las Vegas Field Office',
    'Nevada - USCIS Reno Field Office',
    'New York - USCIS Albany Field Office',
    'New York - USCIS Brooklyn Field Office',
    'New York - USCIS Buffalo Field Office',
    'New York - USCIS Long Island Field Office',
    'New York - USCIS New York City District Office',
    'New York - USCIS Queens Field Office',
    'New York - USCJS Syracuse Field Office',
    'Ohio - USCIS Cincinnati Field Office',
    'Ohio - USCIS Cleveland Field Office',
    'Ohio - USCIS Columbus Field Office',
    'Oregon - USCIS Portland Field Office',
    'Pennsylvania - USCIS Philadelphia Field Office',
    'Pennsylvania - USCIS Pittsburgh Field Office',
    'Rhode Island - USCIS Providence Field Office',
    'South Carolina - USCIS Charleston Field Office',
    'South Carolina - USCIS Greer Field Office',
    'Tennessee - USCIS Memphis Field Office',
    'Tennessee - USCIS Nashville Field Office',
    'Texas - USCIS Central Region Office',
    'Texas - USCIS Dallas Field Office',
    'Texas - USCIS El Paso Field Office',
    'Texas - USCIS Harlingen Field Office',
    'Texas - USCIS Houston Field Office',
    'Texas - USCIS San Antonio Field Office',
    'Texas - USCIS Texas Service Center',
    'Utah - USCIS Salt Lake City Field Office',
    'Virginia - USCIS Norfolk Field Office',
    'Virginia - USCIS Potomac Service Center',
    'Virginia - USCIS Washington Field Office',
    'Virgin Islands - USCIS Charlotte Amalie VI Field Office',
    'Vermont - USCIS Northeast Regional Office',
    'Vermont - USCIS St Albans Field Office',
    'Vermont - USCIS Vermont Service Center',
    'Washington - USCIS Seattle Field Office',
    'Washington - USCIS Spokane Field Office',
    'Washington - USCIS Yakima Field Office',
    'Wisconsin - USCIS Milwaukee Field Office',
]
