"""Part 9 of Form I-485 (General Eligibility and Inadmissibility Grounds), Items 1-84, as short thematic steps.

Every question keeps the official meaning and order; nothing is merged, dropped or reworded into a conclusion. A "Yes" opens a
required explanation that OG places in Part 14 (the customer never types a page / part / item number). Structured follow-ups exist
only where the form itself has them: Item 1 organizations (Items 2-9), Items 20-21 (chained on 19), Item 24's clemency note, Items 29,
35.b, 40 (chained), Items 57-64 (public charge) and Items 75 / 84.

OG never turns an answer into a finding. Wording stays neutral: "OG should review this answer".
"""

from app.seed_i485 import UNSURE, only_if, choice
from app.seed_i130 import page, records
from app.seed_i90 import YES_NO
from app.seed_n400 import note, show_any, show_page_any

REF = "Part 9, Item "

EXPLAIN = {
    "generic": ("Explain what happened, including the dates and the place. If you do not remember everything, write what you can — OG will follow up with you.",
                "Explica qué pasó, incluidas las fechas y el lugar. Si no recuerdas todo, escribe lo que puedas: OG te dará seguimiento."),
    "criminal": ("For each event: describe the offense, where and when it happened, whether you were arrested, cited, charged or detained, and the outcome (for example convicted, diversion program, no charges filed, dismissed, jail, probation), including the length of any sentence even if it was suspended. If you do not remember everything, write what you can — OG will follow up.",
                 "Por cada hecho: describe el delito, dónde y cuándo ocurrió, si fuiste arrestado(a), citado(a), acusado(a) o detenido(a), y el resultado (por ejemplo condena, programa de desvío, sin cargos, desestimado, cárcel, libertad condicional), incluida la duración de cualquier sentencia aunque se haya suspendido. Si no recuerdas todo, escribe lo que puedas: OG te dará seguimiento."),
    "intent": ("Explain what you did, or what you intend to do, including the dates and the place.", "Explica qué hiciste, o qué tienes la intención de hacer, incluidas las fechas y el lugar."),
    "relative": ("Explain what your spouse or parent did, including the dates and the place.", "Explica qué hizo tu cónyuge o tu padre o madre, incluidas las fechas y el lugar."),
    "armed": ("Include the name of the country, the name of the military unit or armed group, your rank or position, and your dates of involvement.",
              "Incluye el nombre del país, el nombre de la unidad militar o grupo armado, tu rango o cargo y tus fechas de participación."),
    "unlawful": ("Give the dates you were unlawfully present in the United States, as best you can.", "Indica las fechas en que estuviste presente sin autorización en los Estados Unidos, lo mejor que puedas."),
}


def q(b, name, item, en, es, *, explain="generic", help=None):
    b.field(name, "single_choice", (en, es), ref=REF + item, req=True, opts=YES_NO, help=help)
    if explain:
        b.field(f"{name}_explain", "long_answer", ("Please explain your answer", "Explica tu respuesta"), ref=f"Part 14 (explanation for Part 9, Item {item})", req=True, help=EXPLAIN[explain], maxlen=2000)
        b.rule("show_field", f"{name}_explain", [(name, "equals", "yes")])


def epage(b, key, group, title, desc=None):
    return page(b, key, title, desc, group=group, ctx="applicant")


def build_eligibility(b):
    # ---------------------------------------------------------------- organizations (Items 1-9)
    epage(b, "e_intro", "elig_groups", ("Eligibility questions", "Preguntas de elegibilidad"),
          ("Part 9 of the form asks a series of Yes/No questions. Choose the answer you think is correct. If you answer Yes — or you answer No but are not sure — OG will look at the answer with you.",
           "La Parte 9 del formulario hace una serie de preguntas de Sí/No. Elige la respuesta que crees correcta. Si respondes Sí, o respondes No pero no estás seguro(a), OG revisará la respuesta contigo."))
    b.field("e_intro_note", "paragraph", ("", ""), content=(
        '<span class="block text-[15px] text-slate-700">These questions are the same for everyone. Answering Yes to one does not mean anything is wrong with your application — OG only needs to understand it. The questions are short and grouped by topic.</span>'
        '<span class="block mt-2 text-[13px] text-slate-500">If you are unsure about an answer, choose the one you think is correct and tell us more at the end of this section.</span>',
        '<span class="block text-[15px] text-slate-700">Estas preguntas son las mismas para todos. Responder Sí a una no significa que algo esté mal en tu solicitud: OG solo necesita entenderla. Las preguntas son cortas y están agrupadas por tema.</span>'
        '<span class="block mt-2 text-[13px] text-slate-500">Si no estás seguro(a) de una respuesta, elige la que creas correcta y cuéntanos más al final de esta sección.</span>'))
    b.field("e1", "single_choice", ("Have you EVER been a member of, involved in, or in any way associated with any organization, association, fund, foundation, party, club, society, or similar group in the United States or in any other location in the world?",
                                    "¿Alguna vez has sido miembro de, participado en, o estado de cualquier forma asociado(a) con alguna organización, asociación, fondo, fundación, partido, club, sociedad o grupo similar en los Estados Unidos o en cualquier otro lugar del mundo?"),
            ref=REF + "1", req=True, opts=YES_NO)
    epage(b, "e_orgs", "elig_groups", ("Your organizations", "Tus organizaciones"),
          ("Provide the name, place, nature of the organization, your involvement (role or positions held, whether illicit or legitimate) and the dates. If there are more than two, add them all — OG places the extra ones in Part 14.",
           "Indica el nombre, el lugar, la naturaleza de la organización, tu participación (cargo o puestos, sea ilícita o legítima) y las fechas. Si son más de dos, agrégalas todas: OG coloca las adicionales en la Parte 14."))
    records(b, "e1_orgs", ("Organizations, associations, clubs, parties or similar groups", "Organizaciones, asociaciones, clubes, partidos o grupos similares"), "Part 9, Items 2–9", "i485_org", req=True, max=10)
    show_page_any(b, "e_orgs", [[("e1", "equals", "yes")]])

    # ---------------------------------------------------------------- immigration (Items 10-21)
    epage(b, "e_imm1", "elig_immigration", ("Entry and status", "Entrada y estatus"))
    q(b, "e10", "10", "Have you EVER been denied admission to the United States?", "¿Alguna vez se te ha negado la admisión a los Estados Unidos?")
    q(b, "e11", "11", "Have you EVER been denied a visa to the United States?", "¿Alguna vez se te ha negado una visa para los Estados Unidos?")
    q(b, "e12", "12", "Have you EVER worked in the United States without authorization?", "¿Alguna vez has trabajado en los Estados Unidos sin autorización?")
    q(b, "e13", "13", "Have you EVER violated the terms or conditions of your nonimmigrant status?", "¿Alguna vez has violado los términos o condiciones de tu estatus de no inmigrante?")
    epage(b, "e_imm2", "elig_immigration", ("Proceedings and orders", "Procesos y órdenes"))
    q(b, "e14", "14", "Are you presently or have you EVER been in removal, exclusion, rescission, or deportation proceedings, including expedited removal proceedings?",
      "¿Estás actualmente o has estado ALGUNA VEZ en procedimientos de remoción, exclusión, rescisión o deportación, incluidos los procedimientos de remoción expedita?")
    q(b, "e15", "15", "Have you EVER been issued a final order of exclusion, deportation, or removal?", "¿Alguna vez se te ha emitido una orden final de exclusión, deportación o remoción?")
    q(b, "e16", "16", "Have you EVER had a prior final order of exclusion, deportation, or removal reinstated?", "¿Alguna vez se ha reinstalado una orden final anterior de exclusión, deportación o remoción en tu contra?")
    q(b, "e17", "17", "Have you EVER been granted voluntary departure by an immigration officer or an immigration judge but failed to depart within the allotted time?",
      "¿Alguna vez se te ha concedido la salida voluntaria por un oficial de inmigración o un juez de inmigración pero no saliste dentro del plazo asignado?")
    q(b, "e18", "18", "Have you EVER applied for any kind of relief or protection from removal, exclusion, or deportation?", "¿Alguna vez has solicitado algún tipo de alivio o protección contra la remoción, exclusión o deportación?")
    epage(b, "e_imm3", "elig_immigration", ("J exchange visitor requirement", "Requisito de visitante de intercambio J"))
    q(b, "e19", "19", "Have you EVER been a J nonimmigrant exchange visitor who was subject to the two-year foreign residence requirement?",
      "¿Alguna vez has sido un visitante de intercambio no inmigrante J sujeto al requisito de residencia en el extranjero de dos años?")
    q(b, "e20", "20", "If you answered “Yes” to Item Number 19., have you complied with the foreign residence requirement?", "Si respondiste “Sí” al Ítem 19., ¿has cumplido con el requisito de residencia en el extranjero?", explain=None)
    only_if(b, "e20", ("e19", "equals", "yes"))
    q(b, "e21", "21", "If you answered “Yes” to Item Number 19. and “No” to Item Number 20., have you been granted a waiver or has Department of State issued a favorable waiver recommendation letter for you?",
      "Si respondiste “Sí” al Ítem 19. y “No” al Ítem 20., ¿se te ha concedido una exención o el Departamento de Estado te ha emitido una carta de recomendación favorable de exención?", explain=None)
    show_any(b, "e21", [[("e19", "equals", "yes"), ("e20", "equals", "no")]])

    # ---------------------------------------------------------------- criminal acts and violations (Items 22-41)
    epage(b, "e_crim0", "elig_criminal", ("Criminal acts and violations", "Actos delictivos y violaciones"),
          ("For Items 22–41, answer “Yes” to any question that applies to you, even if your records were sealed or otherwise cleared, or even if anyone told you that you no longer have a record. Answer for events here in the United States or anywhere else in the world.",
           "Para los Ítems 22–41, responde “Sí” a cualquier pregunta que te aplique, aunque tus registros hayan sido sellados o eliminados, o aunque alguien te haya dicho que ya no tienes antecedentes. Responde por hechos ocurridos aquí en los Estados Unidos o en cualquier otro lugar del mundo."))
    q(b, "e22", "22", "Have you EVER been arrested, cited, charged, or permitted to participate in a diversion program (including pre-trial diversion, deferred prosecution, deferred adjudication, or any withheld adjudication), or detained for any reason by any law enforcement official in any country including but not limited to any U.S. immigration official or any official of the U.S. armed forces or U.S. Coast Guard or by a similar official of a country other than the United States?",
      "¿Alguna vez has sido arrestado(a), citado(a), acusado(a) o se te ha permitido participar en un programa de desvío (incluido desvío previo al juicio, enjuiciamiento diferido, adjudicación diferida o cualquier adjudicación retenida), o detenido(a) por cualquier motivo por cualquier oficial de la ley en cualquier país, incluido cualquier oficial de inmigración de EE. UU. o cualquier oficial de las fuerzas armadas o de la Guardia Costera de EE. UU. o por un oficial similar de un país distinto de los Estados Unidos?", explain="criminal")
    q(b, "e23", "23", "Have you EVER committed a crime of any kind (even if you were not arrested, cited, charged with, or tried for that crime, or convicted)?",
      "¿Alguna vez has cometido un delito de cualquier tipo (aunque no hayas sido arrestado(a), citado(a), acusado(a) ni juzgado(a) por ese delito, ni condenado(a))?", explain="criminal")
    q(b, "e24", "24", "Have you EVER pled guilty to or been convicted of a crime or offense (even if the violation was subsequently expunged or sealed by a court, or if you were granted a pardon, amnesty, a rehabilitation decree, or other act of clemency)?",
      "¿Alguna vez te has declarado culpable o has sido condenado(a) por un delito o infracción (aunque la violación haya sido borrada o sellada posteriormente por un tribunal, o aunque se te haya concedido un indulto, amnistía, un decreto de rehabilitación u otro acto de clemencia)?", explain="criminal")
    b.field("e24_clemency", "single_choice", ("Were you the beneficiary of a pardon, amnesty, a rehabilitation decree, or other act of clemency?", "¿Fuiste beneficiario(a) de un indulto, amnistía, un decreto de rehabilitación u otro acto de clemencia?"),
            ref=REF + "24 (NOTE)", req=True, opts=YES_NO,
            help=("The form says to provide documentation of that post-conviction action; OG will list it in your documents.", "El formulario indica que se debe presentar documentación de esa acción posterior a la condena; OG la incluirá en tu lista de documentos."))
    only_if(b, "e24_clemency", ("e24", "equals", "yes"))
    q(b, "e25", "25", "Have you EVER been ordered punished by a judge or had conditions imposed on you that restrained your liberty (such as a prison sentence, suspended sentence, house arrest, parole, alternative sentencing, drug or alcohol treatment, rehabilitative programs or classes, probation, or community service)?",
      "¿Alguna vez un juez ha ordenado que se te castigue o se te han impuesto condiciones que restringieron tu libertad (como una sentencia de prisión, sentencia suspendida, arresto domiciliario, libertad condicional, sentencia alternativa, tratamiento por drogas o alcohol, programas o clases de rehabilitación, período de prueba o servicio comunitario)?", explain="criminal")
    epage(b, "e_crim2", "elig_criminal", ("Controlled substances", "Sustancias controladas"))
    q(b, "e26", "26", "Have you EVER violated (or attempted or conspired to violate) any controlled substance law or regulation of a state, the United States, or a foreign country?",
      "¿Alguna vez has violado (o intentado o conspirado para violar) alguna ley o reglamento de sustancias controladas de un estado, de los Estados Unidos o de un país extranjero?", explain="criminal")
    q(b, "e27", "27", "Have you EVER trafficked in or benefited from, or knowingly aided, abetted, assisted, conspired or colluded in the illegal trafficking of any controlled substances, such as chemicals, illegal drugs, or narcotics?",
      "¿Alguna vez has traficado o te has beneficiado del tráfico ilegal de sustancias controladas, como productos químicos, drogas ilegales o narcóticos, o has ayudado, instigado, asistido, conspirado o coludido a sabiendas en dicho tráfico?", explain="criminal")
    q(b, "e28", "28", "Are you the spouse, son, or daughter of an alien who illicitly trafficked or aided (or otherwise abetted, assisted, conspired, or colluded) in the illicit trafficking of a controlled substance, such as chemicals, illegal drugs, or narcotics and you obtained, within the last 5 years, any financial or other benefit from this activity of your spouse or parent?",
      "¿Eres cónyuge, hijo(a) de un extranjero que traficó ilícitamente o ayudó (o de otra manera instigó, asistió, conspiró o coludió) en el tráfico ilícito de una sustancia controlada, como productos químicos, drogas ilegales o narcóticos, y obtuviste, en los últimos 5 años, algún beneficio financiero o de otro tipo de esta actividad de tu cónyuge o de tu padre o madre?", explain="generic")
    q(b, "e29", "29", "If your answer to Item Number 28. is “Yes,” did you know or should you have reasonably known that the financial or other benefit you obtained resulted from this activity of your spouse or parent?",
      "Si tu respuesta al Ítem 28. es “Sí”, ¿sabías o razonablemente deberías haber sabido que el beneficio financiero o de otro tipo que obtuviste resultó de esta actividad de tu cónyuge o de tu padre o madre?", explain=None)
    only_if(b, "e29", ("e28", "equals", "yes"))
    epage(b, "e_crim3", "elig_criminal", ("Prostitution and other conduct", "Prostitución y otra conducta"))
    q(b, "e30", "30", "Have you EVER engaged in prostitution or are you coming to the United States to engage in prostitution?", "¿Alguna vez te has dedicado a la prostitución o vienes a los Estados Unidos para dedicarte a la prostitución?")
    q(b, "e31", "31", "Have you EVER directly or indirectly procured or attempted to procure, or imported prostitutes or persons for the purpose of prostitution?", "¿Alguna vez has conseguido o intentado conseguir, directa o indirectamente, o has importado prostitutas o personas con el propósito de prostitución?")
    q(b, "e32", "32", "Have you EVER received any proceeds or money from prostitution?", "¿Alguna vez has recibido ganancias o dinero de la prostitución?")
    q(b, "e33", "33", "Do you intend to engage in illegal gambling or any other form of commercialized vice, such as prostitution, bootlegging, or the sale of child pornography, while in the United States?",
      "¿Tienes la intención de dedicarte al juego ilegal o a cualquier otra forma de vicio comercializado, como prostitución, contrabando de licor o la venta de pornografía infantil, mientras estés en los Estados Unidos?", explain="intent")
    q(b, "e34", "34", "Have you EVER exercised immunity (diplomatic or otherwise) to avoid being prosecuted for a criminal offense in the United States?", "¿Alguna vez has ejercido inmunidad (diplomática o de otro tipo) para evitar ser procesado(a) por un delito en los Estados Unidos?")
    epage(b, "e_crim4", "elig_criminal", ("Government official and trafficking", "Funcionario de gobierno y trata de personas"))
    q(b, "e35a", "35.a", "Have you EVER served as a foreign government official?", "¿Alguna vez has servido como funcionario de un gobierno extranjero?")
    q(b, "e35b", "35.b", "If your answer to Item Number 35.a. is “Yes,” have you EVER been responsible for, enforced, or directly carried out violations of religious freedoms?",
      "Si tu respuesta al Ítem 35.a. es “Sí”, ¿alguna vez has sido responsable de, hecho cumplir o llevado a cabo directamente violaciones de las libertades religiosas?", explain=None)
    only_if(b, "e35b", ("e35a", "equals", "yes"))
    q(b, "e36", "36", "Have you EVER induced by force, fraud, or coercion (or otherwise been involved in) the trafficking of another person for commercial sex acts (sex trafficking)?",
      "¿Alguna vez has inducido mediante fuerza, fraude o coacción (o de otra manera has estado involucrado(a) en) la trata de otra persona para actos sexuales comerciales (trata sexual)?")
    b.field("e36_note", "paragraph", ("", ""), content=(
        '<span class="block text-[13px] text-slate-500">Sex trafficking involves inducing or causing an adult to engage in a commercial sex act (any sex act performed for anything of value) through fraud, force, or coercion, or inducing or causing any person under 18 years of age to engage in a commercial sex act (even without force, fraud, or coercion). It may include recruiting, enticing, harboring, transporting, providing, obtaining, advertising, maintaining, patronizing, or soliciting a person for that purpose, or knowingly benefiting financially from participation in a venture involving sex trafficking. (Summary of the note printed on the form.)</span>',
        '<span class="block text-[13px] text-slate-500">La trata sexual consiste en inducir o hacer que un adulto participe en un acto sexual comercial (cualquier acto sexual realizado a cambio de algo de valor) mediante fraude, fuerza o coacción, o inducir o hacer que cualquier persona menor de 18 años participe en un acto sexual comercial (incluso sin fuerza, fraude ni coacción). Puede incluir reclutar, seducir, albergar, transportar, proporcionar, obtener, anunciar, mantener, patrocinar o solicitar a una persona para ese fin, o beneficiarse económicamente a sabiendas de la participación en una empresa de trata sexual. (Resumen de la nota impresa en el formulario.)</span>'))
    q(b, "e37", "37", "Have you EVER trafficked a person into involuntary servitude, peonage, debt bondage, or slavery?", "¿Alguna vez has traficado a una persona para servidumbre involuntaria, peonaje, servidumbre por deudas o esclavitud?",
      help=("Trafficking includes recruiting, harboring, transporting, providing, or obtaining a person for labor or services through the use of force, fraud, or coercion.", "La trata incluye reclutar, albergar, transportar, proporcionar u obtener a una persona para trabajo o servicios mediante el uso de fuerza, fraude o coacción."))
    epage(b, "e_crim5", "elig_criminal", ("Trafficking and money laundering", "Trata de personas y lavado de dinero"))
    q(b, "e38", "38", "Have you EVER knowingly aided, abetted, assisted, conspired, or colluded with others in trafficking in persons for commercial sex acts or involuntary servitude, peonage, debt bondage, or slavery?",
      "¿Alguna vez has ayudado, instigado, asistido, conspirado o coludido a sabiendas con otros en la trata de personas para actos sexuales comerciales o servidumbre involuntaria, peonaje, servidumbre por deudas o esclavitud?")
    q(b, "e39", "39", "Are you the spouse, son, or daughter of an alien who engaged in the trafficking in persons and have received or obtained, within the last 5 years, any financial or other benefits from this activity of your spouse or your parent?",
      "¿Eres cónyuge, hijo(a) de un extranjero que participó en la trata de personas y has recibido u obtenido, en los últimos 5 años, algún beneficio financiero o de otro tipo de esta actividad de tu cónyuge o de tu padre o madre?")
    q(b, "e40", "40", "If your answer is “Yes” to Item Number 39., did you know or reasonably should have known that this benefit resulted from this activity of your spouse or parent?",
      "Si tu respuesta es “Sí” al Ítem 39., ¿sabías o razonablemente deberías haber sabido que este beneficio resultó de esta actividad de tu cónyuge o de tu padre o madre?", explain=None)
    only_if(b, "e40", ("e39", "equals", "yes"))
    q(b, "e41", "41", "Have you EVER engaged in money laundering or have you EVER knowingly aided, assisted, abetted, conspired, or colluded with others in money laundering or do you seek to enter the United States to engage in such activity?",
      "¿Alguna vez has participado en el lavado de dinero o has ayudado, asistido, instigado, conspirado o coludido a sabiendas con otros en el lavado de dinero, o buscas entrar a los Estados Unidos para participar en dicha actividad?")

    # ---------------------------------------------------------------- security and related (Items 42-55)
    epage(b, "e_sec1", "elig_security", ("Security and related — what you intend to do", "Seguridad y temas relacionados — lo que piensas hacer"), ("Do you intend to…", "¿Tienes la intención de…"))
    q(b, "e42a", "42.a", "Engage in any activity that violates or evades any law relating to espionage (including spying) or sabotage in the United States?", "¿Participar en cualquier actividad que viole o evada cualquier ley relacionada con espionaje (incluido el espionaje) o sabotaje en los Estados Unidos?", explain="intent")
    q(b, "e42b", "42.b", "Engage in any activity in the United States that violates or evades any law prohibiting the export from the United States of goods, technology, or sensitive information?", "¿Participar en cualquier actividad en los Estados Unidos que viole o evada cualquier ley que prohíba la exportación desde los Estados Unidos de bienes, tecnología o información sensible?", explain="intent")
    q(b, "e42c", "42.c", "Engage in any activity whose purpose includes opposing, controlling, or overthrowing the U.S. Government by force, violence, or other unlawful means while in the United States?", "¿Participar en cualquier actividad cuyo propósito incluya oponerse, controlar o derrocar al gobierno de EE. UU. por la fuerza, la violencia u otros medios ilegales mientras estés en los Estados Unidos?", explain="intent")
    q(b, "e42d", "42.d", "Engage in any other unlawful activity?", "¿Participar en cualquier otra actividad ilegal?", explain="intent")
    epage(b, "e_sec2", "elig_security", ("Security and related — weapons and violence", "Seguridad y temas relacionados — armas y violencia"), ("Have you EVER…", "¿Alguna vez has…"))
    q(b, "e43a", "43.a", "Received any weapons training, paramilitary training, or other military-type training?", "¿Recibido entrenamiento con armas, entrenamiento paramilitar u otro entrenamiento de tipo militar?")
    q(b, "e43b", "43.b", "Committed kidnapping, assassination, or hijacking or sabotage of a conveyance (including an aircraft, vessel, vehicle, or train)?", "¿Cometido secuestro, asesinato, o secuestro o sabotaje de un medio de transporte (incluidos una aeronave, embarcación, vehículo o tren)?")
    q(b, "e43c", "43.c", "Used a weapon or explosive or any dangerous device with the intent to endanger the safety of another person or people or cause damage to property?", "¿Usado un arma o explosivo o cualquier dispositivo peligroso con la intención de poner en peligro la seguridad de otra persona o personas o causar daño a la propiedad?")
    q(b, "e43d", "43.d", "Threatened, attempted, conspired, prepared, or planned to do any of the things described in Item Numbers 43.b. - 43.c.?", "¿Amenazado, intentado, conspirado, preparado o planeado hacer cualquiera de las cosas descritas en los Ítems 43.b. - 43.c.?")
    q(b, "e43e", "43.e", "Incited, under circumstances indicating an intention to cause death or serious bodily harm/injury, any of the activities described in Item Numbers 43.b. - 43.c.?", "¿Incitado, en circunstancias que indican la intención de causar la muerte o daño/lesión corporal grave, cualquiera de las actividades descritas en los Ítems 43.b. - 43.c.?")
    epage(b, "e_sec3", "elig_security", ("Security and related — groups and support", "Seguridad y temas relacionados — grupos y apoyo"), ("Have you EVER…", "¿Alguna vez has…"))
    q(b, "e43f", "43.f", "Participated in, or been a member of, a group or organization that did any of the activities described in Item Numbers 43.b. - 43.e.?", "¿Participado en, o sido miembro de, un grupo u organización que realizó cualquiera de las actividades descritas en los Ítems 43.b. - 43.e.?")
    q(b, "e43g", "43.g", "Recruited members or asked for money or things of value for a group or organization that did any of the activities described in Item Numbers 43.b. - 43.e.?", "¿Reclutado miembros o pedido dinero u objetos de valor para un grupo u organización que realizó cualquiera de las actividades descritas en los Ítems 43.b. - 43.e.?")
    q(b, "e43h", "43.h", "Provided money, a thing of value, services or labor, or any other assistance or support for any of the activities described in Item Numbers 43.b. - 43.e.?", "¿Proporcionado dinero, algo de valor, servicios o mano de obra, o cualquier otra asistencia o apoyo para cualquiera de las actividades descritas en los Ítems 43.b. - 43.e.?")
    q(b, "e43i", "43.i", "Provided money, a thing of value, services or labor, or any other assistance or support for an individual, group, or organization who did any of the activities described in Item Numbers 43.b. - 43.e.?", "¿Proporcionado dinero, algo de valor, servicios o mano de obra, o cualquier otra asistencia o apoyo para una persona, grupo u organización que realizó cualquiera de las actividades descritas en los Ítems 43.b. - 43.e.?")
    q(b, "e44", "44", "Do you intend to engage in any of the activities listed in any part of Item Numbers 43.b. - 43.e.?", "¿Tienes la intención de participar en cualquiera de las actividades enumeradas en cualquier parte de los Ítems 43.b. - 43.e.?", explain="intent")
    q(b, "e45", "45", "Do you intend to engage in any activity that could endanger the welfare, safety, or security of the United States?", "¿Tienes la intención de participar en cualquier actividad que pueda poner en peligro el bienestar, la seguridad o la protección de los Estados Unidos?", explain="intent")
    epage(b, "e_sec4", "elig_security", ("Family members, weapons and detention", "Familiares, armas y detención"))
    q(b, "e46", "46", "Are you the spouse or child of an individual who EVER engaged in any of the activities listed in Item Numbers 43.b. - 43.i.?", "¿Eres cónyuge o hijo(a) de una persona que ALGUNA VEZ participó en cualquiera de las actividades enumeradas en los Ítems 43.b. - 43.i.?", explain="relative")
    q(b, "e47", "47", "Have you EVER sold, provided, or transported weapons, or assisted any person in selling, providing, or transporting weapons, which you knew or believed would be used against another person?", "¿Alguna vez has vendido, proporcionado o transportado armas, o ayudado a cualquier persona a vender, proporcionar o transportar armas, que sabías o creías que serían usadas contra otra persona?")
    q(b, "e48", "48", "Have you EVER worked, volunteered, or otherwise served in any prison, jail, prison camp, detention facility, labor camp, or any other place where people were detained, or have you EVER directed or participated in any other activity that involved detaining people?", "¿Alguna vez has trabajado, hecho voluntariado o servido de otra manera en alguna prisión, cárcel, campo de prisioneros, centro de detención, campo de trabajo o cualquier otro lugar donde se detenía a personas, o has dirigido o participado en cualquier otra actividad que implicara detener a personas?")
    q(b, "e49", "49", "Have you EVER been a member of, assisted, or participated in any group, unit, or organization of any kind in which you or other persons used any type of weapon against any person or threatened to do so?", "¿Alguna vez has sido miembro de, ayudado o participado en cualquier grupo, unidad u organización de cualquier tipo en el que tú u otras personas usaron cualquier tipo de arma contra cualquier persona o amenazaron con hacerlo?")
    epage(b, "e_sec5", "elig_security", ("Military, armed groups and affiliations", "Grupos militares, armados y afiliaciones"))
    q(b, "e50", "50", "Have you EVER served in, been a member of, assisted (helped), or participated in any military or police unit?", "¿Alguna vez has servido en, sido miembro de, ayudado o participado en cualquier unidad militar o policial?", explain="armed")
    q(b, "e51", "51", "Have you EVER served in, been a member of, assisted (helped), or participated in any armed group (a group that carries weapons), for example: paramilitary unit (a group of people who act like a military group, but are not part of the official military), self-defense unit, vigilante unit, rebel group, or guerrilla group?", "¿Alguna vez has servido en, sido miembro de, ayudado o participado en cualquier grupo armado (un grupo que porta armas), por ejemplo: unidad paramilitar (un grupo de personas que actúan como un grupo militar pero no forman parte del ejército oficial), unidad de autodefensa, unidad de vigilantes, grupo rebelde o grupo guerrillero?", explain="armed")
    q(b, "e52", "52", "Have you EVER been a member of, or in any way affiliated with, the Communist Party or any totalitarian party (in the United States or abroad)?", "¿Alguna vez has sido miembro de, o de cualquier forma afiliado(a) con, el Partido Comunista o cualquier partido totalitario (en los Estados Unidos o en el extranjero)?")
    epage(b, "e_sec6", "elig_security", ("Serious harm and minors", "Daño grave y menores de edad"), ("Have you EVER ordered, incited, called for, committed, assisted, helped with, or otherwise participated in any of the following:", "¿Alguna vez has ordenado, incitado, pedido, cometido, ayudado, asistido o participado de otra manera en cualquiera de los siguientes actos:"))
    q(b, "e53a", "53.a", "Torture?", "¿Tortura?")
    q(b, "e53b", "53.b", "Genocide?", "¿Genocidio?")
    q(b, "e53c", "53.c", "Killing, or trying to kill, any person?", "¿Matar, o intentar matar, a cualquier persona?")
    q(b, "e53d", "53.d", "Intentionally and severely injuring or trying to injure any person?", "¿Herir intencional y gravemente, o intentar herir, a cualquier persona?")
    epage(b, "e_sec7", "elig_security", ("Persons under 15", "Personas menores de 15 años"))
    q(b, "e54", "54", "Have you EVER recruited, enlisted, conscripted, or used any person under 15 years of age to take part in hostilities or to serve in or help an armed force or group, or attempted or worked with others to do so?", "¿Alguna vez has reclutado, alistado, reclutado por la fuerza o usado a cualquier persona menor de 15 años para participar en hostilidades o para servir en o ayudar a una fuerza o grupo armado, o intentado o trabajado con otros para hacerlo?")
    q(b, "e55", "55", "Have you EVER used any person under 15 years of age to take part in hostilities, for instance, participating in combat or providing services related to combat (such as sabotage or serving as a courier) or providing support services (such as transporting supplies), or attempted or worked with others to do so?", "¿Alguna vez has usado a cualquier persona menor de 15 años para participar en hostilidades, por ejemplo, participando en combate o prestando servicios relacionados con el combate (como sabotaje o servir de mensajero) o prestando servicios de apoyo (como transportar suministros), o intentado o trabajado con otros para hacerlo?")

    # ---------------------------------------------------------------- public charge (Items 56-64)
    epage(b, "e_pc56", "elig_public_charge", ("Public charge — exempt categories", "Carga pública — categorías exentas"),
          ("Each applicant subject to the public charge ground of inadmissibility completes Items 57–64. If you fall under one of the exempt categories on the form, select it and skip Items 57–64. OG will confirm this with you.",
           "Cada solicitante sujeto al motivo de inadmisibilidad por carga pública completa los Ítems 57–64. Si te encuentras en una de las categorías exentas del formulario, selecciónala y omite los Ítems 57–64. OG lo confirmará contigo."))
    choice(b, "e56", ("I am exempt from the public charge ground of inadmissibility because I am a/an (select only one box):", "Estoy exento(a) del motivo de inadmisibilidad por carga pública porque soy (selecciona solo una casilla):"), REF + "56", [
        ("pc_asylee", "Asylee (Form I-589 or Form I-730)", "Asilado(a) (Formulario I-589 o I-730)"),
        ("pc_u_245m", "Victim of Qualifying Criminal Activity (U Nonimmigrant) under INA section 245(m) (Form I-918, Form I-918A, or Form I-929)", "Víctima de actividad delictiva calificada (no inmigrante U) bajo la sección 245(m) de la INA (Formulario I-918, I-918A o I-929)"),
        ("pc_refugee", "Refugee (Form I-590 or Form I-730)", "Refugiado(a) (Formulario I-590 o I-730)"),
        ("pc_afghan_iraqi", "Certain Afghan or Iraqi National (Form I-360 or Form DS-157)", "Ciertos nacionales de Afganistán o Irak (Formulario I-360 o DS-157)"),
        ("pc_t_245l", "Human Trafficking Victim (T nonimmigrant) under INA section 245(l) (Form I-914 or Form I-914A)", "Víctima de trata de personas (no inmigrante T) bajo la sección 245(l) de la INA (Formulario I-914 o I-914A)"),
        ("pc_sij", "Special Immigrant Juvenile (Form I-360)", "Inmigrante Juvenil Especial (Formulario I-360)"),
        ("pc_vawa", "VAWA Self-Petitioner (Form I-360)", "Autopeticionario(a) VAWA (Formulario I-360)"),
        ("pc_caa", "Cuban Adjustment Act", "Ley de Ajuste Cubano"),
        ("pc_valid_u", "Any category other than INA section 245(m), but you are in valid U nonimmigrant status at the time you file your application for adjustment of status. (This exemption only applies if, at the time of the adjudication of Form I-485, you are still in valid U nonimmigrant status.)", "Cualquier categoría distinta de la sección 245(m) de la INA, pero estás en estatus válido de no inmigrante U al presentar tu solicitud de ajuste de estatus. (Esta exención solo aplica si, al momento de la adjudicación del Formulario I-485, sigues en estatus válido de no inmigrante U.)"),
        ("pc_pending_t", "Any category other than INA section 245(l), but you either have a pending application for T nonimmigrant status (Form I-914) that sets forth a prima facie case for eligibility or are in valid T nonimmigrant status at the time you file your application for adjustment of status. (This exemption only applies if your Form I-914 is still pending and deemed to be prima facie eligible or you are in valid T nonimmigrant status when we adjudicate your adjustment of status application.)", "Cualquier categoría distinta de la sección 245(l) de la INA, pero tienes una solicitud pendiente de estatus de no inmigrante T (Formulario I-914) que establece un caso prima facie de elegibilidad o estás en estatus válido de no inmigrante T al presentar tu solicitud de ajuste de estatus. (Esta exención solo aplica si tu Formulario I-914 sigue pendiente y se considera prima facie elegible o estás en estatus válido de no inmigrante T cuando adjudiquemos tu solicitud de ajuste de estatus.)"),
        ("pc_hrifa_battered", "Dependent Status under the Haitian Refugee Immigrant Fairness Act for Battered Spouses and Children", "Estatus de dependiente bajo la Ley de Equidad para Inmigrantes Refugiados Haitianos para cónyuges e hijos maltratados"),
        ("pc_hrifa", "Dependent Status under the Haitian Refugee Immigrant Fairness Act", "Estatus de dependiente bajo la Ley de Equidad para Inmigrantes Refugiados Haitianos"),
        ("pc_caa_battered", "Cuban Adjustment Act for Battered Spouses and Children", "Ley de Ajuste Cubano para cónyuges e hijos maltratados"),
        ("pc_lautenberg", "A Lautenberg Parolee", "Parolado(a) Lautenberg"),
        ("pc_registry", "Continuous Residence in the United States Since Before January 1, 1972 (“Registry”)", "Residencia continua en los Estados Unidos desde antes del 1 de enero de 1972 (“Registro”)"),
        ("pc_nacara", "Nicaraguans and Other Central Americans under section 203 of the Nicaraguan Adjustment and Central American Relief Act (NACARA)", "Nicaragüenses y otros centroamericanos bajo la sección 203 de la Ley NACARA"),
        ("pc_polish_hungarian", "Polish or Hungarian Parolee", "Parolado(a) polaco(a) o húngaro(a)"),
        ("pc_amerasian", "Amerasian Homecoming Act", "Ley de Regreso a Casa de los Amerasiáticos"),
        ("pc_vietnam_laos", "National of Vietnam, Cambodia, or Laos Applying under the Foreign Operations, Export Financing, and Related Programs", "Nacional de Vietnam, Camboya o Laos que solicita bajo la Ley de Operaciones Exteriores, Financiamiento de Exportaciones y Programas Relacionados"),
        ("pc_cuban_haitian", "Cuban and Haitian Entrants Applying for Adjustment of Status under section 202 of the Immigration Reform and Control Act of 1986", "Entrantes cubanos y haitianos que solicitan el ajuste de estatus bajo la sección 202 de la Ley de Reforma y Control de la Inmigración de 1986"),
        ("pc_american_indian", "American Indian Born in Canada (INA section 289) or the Texas Band of Kickapoo Indians of the Kickapoo Tribe of Oklahoma, Public Law 97-429 (Jan. 8, 1983)", "Indígena americano nacido en Canadá (sección 289 de la INA) o la Banda Kickapoo de Texas de la Tribu Kickapoo de Oklahoma, Ley Pública 97-429 (8 de enero de 1983)"),
        ("pc_liberian", "Section 7611 of the National Defense Authorization Act for Fiscal Year 2020 (Liberian Refugee Immigration Fairness)", "Sección 7611 de la Ley de Autorización de Defensa Nacional para el Año Fiscal 2020 (Equidad Migratoria para Refugiados Liberianos)"),
        ("pc_syrian", "Syrian National Adjusting Status under Public Law 106-378", "Nacional de Siria que ajusta su estatus bajo la Ley Pública 106-378"),
        ("pc_ndaa", "Spouse, Child, or Parent of a U.S. Active-Duty Service Member in the Armed Forces under the National Defense Authorization Act (NDAA) (Form I-130 or Form I-360)", "Cónyuge, hijo(a) o padre/madre de un miembro del servicio activo de las fuerzas armadas de EE. UU. bajo la Ley de Autorización de Defensa Nacional (NDAA) (Formulario I-130 o I-360)"),
        ("not_exempt", "I do not fall under any of the exempt categories listed above and will complete Item Numbers 57. - 64.", "No estoy en ninguna de las categorías exentas indicadas arriba y completaré los Ítems 57. - 64."),
        UNSURE])
    epage(b, "e_pc57", "elig_public_charge", ("Public charge — household", "Carga pública — hogar"), ("Items 57–60 ask about your household. Give your best estimate.", "Los Ítems 57–60 preguntan sobre tu hogar. Da tu mejor estimación."))
    b.field("e57", "long_answer", ("Describe your family status (for example, your household size).", "Describe tu situación familiar (por ejemplo, el tamaño de tu hogar)."), ref=REF + "57", req=True, maxlen=500)
    choice(b, "e58", ("Indicate your annual household income.", "Indica el ingreso anual de tu hogar."), REF + "58", [("i1", "$0-27,000", "$0-27,000"), ("i2", "$27,001-52,000", "$27,001-52,000"), ("i3", "$52,001-85,000", "$52,001-85,000"), ("i4", "$85,001-141,000", "$85,001-141,000"), ("i5", "Over $141,000", "Más de $141,000")])
    choice(b, "e59", ("Identify the total value of your household assets.", "Indica el valor total de los activos de tu hogar."), REF + "59", [("a1", "$0-18,400", "$0-18,400"), ("a2", "$18,401-136,000", "$18,401-136,000"), ("a3", "$136,001-321,400", "$136,001-321,400"), ("a4", "$321,401-707,100", "$321,401-707,100"), ("a5", "Over $707,100", "Más de $707,100")])
    choice(b, "e60", ("Identify the total value of your household liabilities (including both secured and unsecured liabilities).", "Indica el valor total de los pasivos de tu hogar (incluidos pasivos garantizados y no garantizados)."), REF + "60", [("l1", "$0", "$0"), ("l2", "$1-10,100", "$1-10,100"), ("l3", "$10,101-57,700", "$10,101-57,700"), ("l4", "$57,701-186,800", "$57,701-186,800"), ("l5", "Over $186,800", "Más de $186,800")])
    epage(b, "e_pc61", "elig_public_charge", ("Public charge — education, skills and benefits", "Carga pública — estudios, habilidades y beneficios"))
    choice(b, "e61", ("What is the highest level of education you have completed?", "¿Cuál es el nivel más alto de educación que has completado?"), REF + "61", [
        ("less_than_hs", "Less than a high school diploma", "Menos que un diploma de escuela secundaria"), ("hs", "High school diploma, GED, or alternative credential", "Diploma de escuela secundaria, GED o credencial alternativa"),
        ("some_college", "1 or more years of college credit, no degree", "1 o más años de créditos universitarios, sin título"), ("associate", "Associate's degree", "Título de asociado"), ("bachelor", "Bachelor's degree", "Licenciatura"),
        ("master", "Master's degree", "Maestría"), ("professional", "Professional degree (JD, MD, DMD, etc.)", "Título profesional (JD, MD, DMD, etc.)"), ("doctorate", "Doctorate degree", "Doctorado")])
    b.field("e61_grade", "short_answer", ("Highest grade of school you have completed", "Grado más alto de escuela que has completado"), ref=REF + "61 (highest grade)", req=True, maxlen=30)
    only_if(b, "e61_grade", ("e61", "equals", "less_than_hs"))
    b.field("e62", "long_answer", ("List your skills (for example, certifications, licenses, skills obtained through work experience, and educational certificates).", "Enumera tus habilidades (por ejemplo, certificaciones, licencias, habilidades obtenidas por experiencia laboral y certificados educativos)."), ref=REF + "62", req=True, maxlen=800)
    b.field("e62_certs", "long_answer", ("List of certifications (if any)", "Lista de certificaciones (si tienes)"), ref=REF + "62 (List of Certifications)", maxlen=800)
    q(b, "e63", "63", "Have you ever received any means-tested public benefit?", "¿Has recibido alguna vez algún beneficio público sujeto a verificación de recursos?", explain=None)
    epage(b, "e_pc64", "elig_public_charge", ("Public benefits you received", "Beneficios públicos que has recibido"), ("List each benefit, the start and end dates, the dollar amount (if applicable) and the reason you received it.", "Enumera cada beneficio, las fechas de inicio y fin, el monto en dólares (si aplica) y el motivo por el que lo recibiste."))
    records(b, "e64", ("Means-tested public benefits received", "Beneficios públicos sujetos a verificación de recursos recibidos"), REF + "64", "i485_benefit", req=True, max=10)
    show_page_any(b, "e_pc64", [[("e63", "equals", "yes"), ("e56", "equals", "not_exempt")], [("e63", "equals", "yes"), ("e56", "equals", "unsure")]])
    for page_key in ("e_pc57", "e_pc61"):
        show_page_any(b, page_key, [[("e56", "equals", "not_exempt")], [("e56", "equals", "unsure")]])

    # ---------------------------------------------------------------- illegal entries / immigration violations (Items 65-76)
    epage(b, "e_vio1", "elig_violations", ("Illegal entries and other immigration violations", "Entradas ilegales y otras violaciones migratorias"))
    q(b, "e65", "65", "Have you EVER failed or refused to attend or to remain in attendance at any removal proceeding filed against you on or after April 1, 1997?", "¿Alguna vez has dejado de asistir, o te has negado a asistir o a permanecer presente, en algún procedimiento de remoción presentado en tu contra a partir del 1 de abril de 1997?",
      help=("If Yes, the form asks for a written statement explaining why, including any reasonable cause — write it in the box that appears.", "Si respondes Sí, el formulario pide una declaración escrita que explique por qué, incluida cualquier causa razonable; escríbela en el cuadro que aparece."))
    q(b, "e66", "66", "Have you EVER submitted altered, fraudulent, or counterfeit documentation to any U.S. Government official to obtain or attempt to obtain any immigration benefit, including a visa or entry into the United States?", "¿Alguna vez has presentado documentación alterada, fraudulenta o falsificada a algún funcionario del gobierno de EE. UU. para obtener o intentar obtener algún beneficio migratorio, incluida una visa o la entrada a los Estados Unidos?")
    q(b, "e67", "67", "Have you EVER lied about, concealed, or misrepresented any information on an application or petition to obtain a visa, other documentation required for entry into the United States, admission to the United States, or any other kind of immigration benefit?", "¿Alguna vez has mentido, ocultado o tergiversado información en una solicitud o petición para obtener una visa, otra documentación requerida para la entrada a los Estados Unidos, la admisión a los Estados Unidos o cualquier otro tipo de beneficio migratorio?")
    q(b, "e68", "68", "Have you EVER falsely claimed to be a U.S. citizen (in writing or any other way)?", "¿Alguna vez has afirmado falsamente ser ciudadano(a) de EE. UU. (por escrito o de cualquier otra manera)?")
    q(b, "e69", "69", "Have you EVER been a stowaway on a vessel or aircraft arriving in the United States?", "¿Alguna vez has sido polizón en una embarcación o aeronave que llegaba a los Estados Unidos?")
    epage(b, "e_vio2", "elig_violations", ("Smuggling and fraud penalties", "Contrabando y sanciones por fraude"))
    q(b, "e70", "70", "Have you EVER knowingly encouraged, induced, assisted, abetted, or aided any alien to enter or to try to enter the United States illegally (alien smuggling)?", "¿Alguna vez has alentado, inducido, ayudado, instigado o asistido a sabiendas a algún extranjero a entrar o intentar entrar ilegalmente a los Estados Unidos (contrabando de extranjeros)?")
    q(b, "e71", "71", "Are you under a final order of civil penalty for violating INA section 274C for use of fraudulent documents?", "¿Estás bajo una orden final de sanción civil por violar la sección 274C de la INA por el uso de documentos fraudulentos?")
    epage(b, "e_vio3", "elig_violations", ("Removal, unlawful presence and reentry", "Remoción, presencia sin autorización y reingreso"), ("Removal, unlawful presence, or illegal reentry after previous immigration violations.", "Remoción, presencia sin autorización o reingreso ilegal después de violaciones migratorias anteriores."))
    q(b, "e72", "72", "Have you EVER been excluded, deported, or removed from the United States or have you ever departed the United States on your own after having been ordered excluded, deported, or removed from the United States?", "¿Alguna vez has sido excluido(a), deportado(a) o removido(a) de los Estados Unidos o has salido por tu cuenta de los Estados Unidos después de que se ordenara tu exclusión, deportación o remoción?")
    q(b, "e73", "73", "Have you EVER entered the United States without being inspected and admitted or paroled?", "¿Alguna vez has entrado a los Estados Unidos sin ser inspeccionado(a) y admitido(a) o con parole?")
    q(b, "e74", "74", "Since April 1, 1997, have you been unlawfully present in the United States? You were unlawfully present in the United States if you were present in the United States after the expiration of the period of stay authorized by the Department of Homeland Security (DHS) Secretary or were present in the United States without being admitted or paroled.",
      "Desde el 1 de abril de 1997, ¿has estado presente sin autorización en los Estados Unidos? Estuviste presente sin autorización en los Estados Unidos si estuviste presente después del vencimiento del período de estadía autorizado por el Secretario del Departamento de Seguridad Nacional (DHS) o si estuviste presente sin haber sido admitido(a) o con parole.", explain="unlawful")
    q(b, "e75", "75", "If you answered “Yes” to Item Number 74., was a severe form of trafficking in persons at least one central reason for your unlawful presence in the United States?", "Si respondiste “Sí” al Ítem 74., ¿fue una forma grave de trata de personas al menos una razón central de tu presencia sin autorización en los Estados Unidos?", explain=None,
      help=("Severe trafficking in persons involves sex trafficking induced by force, fraud or coercion (or of a person under 18), or recruiting, harboring, transporting, providing or obtaining a person for labor or services through force, fraud or coercion for the purpose of involuntary servitude, peonage, debt bondage or slavery.", "La trata grave de personas incluye la trata sexual inducida por fuerza, fraude o coacción (o de una persona menor de 18 años), o reclutar, albergar, transportar, proporcionar u obtener a una persona para trabajo o servicios mediante fuerza, fraude o coacción con el fin de someterla a servidumbre involuntaria, peonaje, servidumbre por deudas o esclavitud."))
    only_if(b, "e75", ("e74", "equals", "yes"))
    epage(b, "e_vio4", "elig_violations", ("Reentry without inspection", "Reingreso sin inspección"), ("Since April 1, 1997, have you EVER reentered or attempted to reenter the United States without being inspected and admitted or paroled after:", "Desde el 1 de abril de 1997, ¿alguna vez has reingresado o intentado reingresar a los Estados Unidos sin ser inspeccionado(a) y admitido(a) o con parole después de:"))
    q(b, "e76a", "76.a", "Having been unlawfully present in the United States for more than one year in the aggregate on or after April 1, 1997? You were unlawfully present for more than one year in the aggregate if you count all of the days during all of your stays that you were present after the expiration of the period of stay authorized by the DHS Secretary or were present without being admitted or paroled.",
      "¿Haber estado presente sin autorización en los Estados Unidos por más de un año en total a partir del 1 de abril de 1997? Estuviste presente sin autorización por más de un año en total si cuentas todos los días de todas tus estadías en que estuviste presente después del vencimiento del período de estadía autorizado por el Secretario del DHS o estuviste presente sin haber sido admitido(a) o con parole.", explain="generic")
    q(b, "e76b", "76.b", "Having been deported, excluded, or removed from the United States?", "¿Haber sido deportado(a), excluido(a) o removido(a) de los Estados Unidos?")

    # ---------------------------------------------------------------- miscellaneous conduct (Items 77-84)
    epage(b, "e_misc1", "elig_misc", ("Other conduct", "Otra conducta"))
    q(b, "e77", "77", "Do you plan to practice polygamy in the United States?", "¿Planeas practicar la poligamia en los Estados Unidos?", explain="intent")
    q(b, "e78", "78", "Are you accompanying an alien who is inadmissible and who has been certified by a medical officer as helpless from sickness, mental or physical disability, or infancy, and who requires your protection or guardianship, as described in INA section 232(c)?", "¿Estás acompañando a un extranjero que es inadmisible y que ha sido certificado por un oficial médico como indefenso por enfermedad, discapacidad mental o física, o por minoría de edad, y que requiere tu protección o tutela, según lo descrito en la sección 232(c) de la INA?")
    q(b, "e79", "79", "Have you EVER assisted in detaining, retaining, or withholding custody of a U.S. citizen child outside the United States from a person who has been granted custody of the child?", "¿Alguna vez has ayudado a detener, retener o negar la custodia de un niño(a) ciudadano(a) de EE. UU. fuera de los Estados Unidos a una persona a quien se le haya otorgado la custodia del niño(a)?")
    q(b, "e80", "80", "Have you EVER voted in violation of any Federal, state, or local constitutional provision, statute, ordinance, or regulation in the United States?", "¿Alguna vez has votado en violación de cualquier disposición constitucional, estatuto, ordenanza o reglamento federal, estatal o local en los Estados Unidos?")
    q(b, "e81", "81", "Have you EVER renounced U.S. citizenship to avoid being taxed by the United States?", "¿Alguna vez has renunciado a la ciudadanía de EE. UU. para evitar que los Estados Unidos te cobre impuestos?")
    epage(b, "e_misc2", "elig_misc", ("Military service", "Servicio militar"), ("Have you EVER:", "¿Alguna vez has:"))
    q(b, "e82a", "82.a", "Applied for exemption or discharge from training or service in the U.S. armed forces or in the U.S. National Security Training Corps on the ground that you are an alien?", "¿Solicitado exención o baja del entrenamiento o servicio en las fuerzas armadas de EE. UU. o en el Cuerpo de Entrenamiento de Seguridad Nacional de EE. UU. alegando que eres extranjero(a)?")
    q(b, "e82b", "82.b", "Been relieved or discharged from such training or service on the ground that you are an alien?", "¿Sido relevado(a) o dado(a) de baja de dicho entrenamiento o servicio alegando que eres extranjero(a)?")
    q(b, "e82c", "82.c", "Been convicted of desertion from the U.S. armed forces?", "¿Sido condenado(a) por deserción de las fuerzas armadas de EE. UU.?")
    q(b, "e83", "83", "Have you EVER left or remained outside the United States to avoid or evade training or service in the U.S. armed forces in time of war or a period declared by the President to be a national emergency?", "¿Alguna vez has salido de los Estados Unidos o permanecido fuera de ellos para evitar o eludir el entrenamiento o servicio en las fuerzas armadas de EE. UU. en tiempo de guerra o en un período declarado por el Presidente como emergencia nacional?", explain=None)
    b.field("e84", "short_answer", ("If you answered “Yes” to Item Number 83., what was your nationality or immigration status immediately before you left (for example, U.S. citizen or national, lawful permanent resident, nonimmigrant, parolee, present without admission or parole, or any other status)?",
                                    "Si respondiste “Sí” al Ítem 83., ¿cuál era tu nacionalidad o estatus migratorio inmediatamente antes de salir (por ejemplo, ciudadano(a) o nacional de EE. UU., residente permanente legal, no inmigrante, parolado(a), presente sin admisión o parole, o cualquier otro estatus)?"), ref=REF + "84", req=True, maxlen=120)
    only_if(b, "e84", ("e83", "equals", "yes"))
    b.field("e83_explain", "long_answer", ("Please explain your answer", "Explica tu respuesta"), ref="Part 14 (explanation for Part 9, Item 83)", req=True, help=EXPLAIN["generic"], maxlen=2000)
    only_if(b, "e83_explain", ("e83", "equals", "yes"))

    epage(b, "e_unsure", "elig_misc", ("Anything you were unsure about?", "¿Algo de lo que no estabas seguro(a)?"),
          ("The form says: if you answer No but are unsure of your answer, provide an explanation. Tell us here about any answer you were not sure of. This is optional.", "El formulario indica: si respondes No pero no estás seguro(a) de tu respuesta, da una explicación. Cuéntanos aquí de cualquier respuesta de la que no estabas seguro(a). Es opcional."))
    b.field("e_unsure_notes", "long_answer", ("Answers you were unsure about, and why", "Respuestas de las que no estabas seguro(a), y por qué"), ref="Part 14 (explanations for answers the applicant was unsure about — Part 9)", maxlen=2000)
