"""navigation items

Revision ID: 050e9258588f
Revises: 54396c0d2586
Create Date: 2026-09-18 12:50:00.197502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050e9258588f'
down_revision = '54396c0d2586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nav_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('system_key', sa.String(length=20), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('label_en', sa.String(length=80), nullable=True),
    sa.Column('label_es', sa.String(length=80), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nav_items')
    # ### end Alembic commands ###
