"""Editable page content blocks

Revision ID: 0539ed7f29c0
Revises: 83ac1bd11713
Create Date: 2026-09-03 14:32:55.947281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0539ed7f29c0'
down_revision = '83ac1bd11713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('content_es', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_blocks')
    # ### end Alembic commands ###
