"""case architecture

Revision ID: 0fb7ac30f97e
Revises: 3b1a130a0001
Create Date: 2026-09-18 20:47:03.476993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fb7ac30f97e'
down_revision = '3b1a130a0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('case_type', sa.String(length=40), server_default='other', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('preferred_language', sa.String(length=2), nullable=True),
    sa.Column('origin', sa.String(length=10), server_default='auto', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cases_customer_id'), ['customer_id'], unique=False)

    op.create_table('case_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_notes_case_id'), ['case_id'], unique=False)

    op.create_table('case_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('is_customer', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('relationship_key', sa.String(length=30), server_default='other', nullable=False),
    sa.Column('given_name', sa.String(length=120), nullable=True),
    sa.Column('family_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_people_case_id'), ['case_id'], unique=False)

    op.create_table('case_document_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), server_default='other', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('customer_message', sa.Text(), nullable=True),
    sa.Column('internal_note', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=10), server_default='admin', nullable=False),
    sa.Column('rule_key', sa.String(length=100), nullable=True),
    sa.Column('source_key', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='requested', nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('review_message', sa.Text(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['case_people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_document_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_document_requirements_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_req_case_rule', ['case_id', 'rule_key'], unique=False)

    op.create_table('case_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), server_default='other', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=10), server_default='customer', nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('replaces_id', sa.Integer(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['case_people.id'], ),
    sa.ForeignKeyConstraint(['replaces_id'], ['case_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_documents_case_id'), ['case_id'], unique=False)

    op.create_table('case_application_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role_key', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['case_people.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'person_id', 'role_key', name='uq_case_role')
    )
    with op.batch_alter_table('case_application_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_application_roles_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_application_roles_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_application_roles_submission_id'), ['submission_id'], unique=False)

    op.create_table('case_document_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('attached_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_reason', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['case_documents.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['case_document_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_document_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_document_attachments_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_document_attachments_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('case_person_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('fact_key', sa.String(length=40), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('source_submission_id', sa.Integer(), nullable=True),
    sa.Column('source_form', sa.String(length=20), nullable=True),
    sa.Column('source_field', sa.String(length=100), nullable=True),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('needs_review', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('first_recorded_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['case_people.id'], ),
    sa.ForeignKeyConstraint(['source_submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'fact_key', name='uq_person_fact')
    )
    with op.batch_alter_table('case_person_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_person_facts_person_id'), ['person_id'], unique=False)

    op.create_table('case_requirement_applications',
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['case_document_requirements.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('requirement_id', 'submission_id')
    )
    op.create_table('case_person_fact_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('old_value_json', sa.Text(), nullable=True),
    sa.Column('new_value_json', sa.Text(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fact_id'], ['case_person_facts.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_person_fact_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_person_fact_events_fact_id'), ['fact_id'], unique=False)

    op.create_table('case_person_fact_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fact_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fact_id'], ['case_person_facts.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fact_id', 'submission_id', 'field_name', name='uq_fact_use')
    )
    with op.batch_alter_table('case_person_fact_uses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_person_fact_uses_fact_id'), ['fact_id'], unique=False)

    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_activity_events_case_id'), ['case_id'], unique=False)
        batch_op.create_foreign_key('fk_case_ref', 'cases', ['case_id'], ['id'])

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_form_submissions_case_id'), ['case_id'], unique=False)
        batch_op.create_foreign_key('fk_case_ref', 'cases', ['case_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_case_ref', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_form_submissions_case_id'))
        batch_op.drop_column('case_id')

    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_case_ref', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activity_events_case_id'))
        batch_op.drop_column('case_id')

    with op.batch_alter_table('case_person_fact_uses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_person_fact_uses_fact_id'))

    op.drop_table('case_person_fact_uses')
    with op.batch_alter_table('case_person_fact_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_person_fact_events_fact_id'))

    op.drop_table('case_person_fact_events')
    op.drop_table('case_requirement_applications')
    with op.batch_alter_table('case_person_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_person_facts_person_id'))

    op.drop_table('case_person_facts')
    with op.batch_alter_table('case_document_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_document_attachments_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_case_document_attachments_document_id'))

    op.drop_table('case_document_attachments')
    with op.batch_alter_table('case_application_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_application_roles_submission_id'))
        batch_op.drop_index(batch_op.f('ix_case_application_roles_person_id'))
        batch_op.drop_index(batch_op.f('ix_case_application_roles_case_id'))

    op.drop_table('case_application_roles')
    with op.batch_alter_table('case_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_documents_case_id'))

    op.drop_table('case_documents')
    with op.batch_alter_table('case_document_requirements', schema=None) as batch_op:
        batch_op.drop_index('ix_req_case_rule')
        batch_op.drop_index(batch_op.f('ix_case_document_requirements_case_id'))

    op.drop_table('case_document_requirements')
    with op.batch_alter_table('case_people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_people_case_id'))

    op.drop_table('case_people')
    with op.batch_alter_table('case_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_notes_case_id'))

    op.drop_table('case_notes')
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cases_customer_id'))

    op.drop_table('cases')
    # ### end Alembic commands ###
