"""itin pricing

Revision ID: 0fdc959cb544
Revises: 099a46eb3874
Create Date: 2026-09-24 17:20:02.229293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdc959cb544'
down_revision = '099a46eb3874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itin_price_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label_en', sa.String(length=160), nullable=False),
    sa.Column('label_es', sa.String(length=160), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_itin_price_rule')
    )
    op.create_table('itin_price_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itin_case_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('lines_json', sa.Text(), nullable=True),
    sa.Column('system_estimate_cents', sa.Integer(), nullable=True),
    sa.Column('final_total_cents', sa.Integer(), nullable=True),
    sa.Column('previous_total_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=True),
    sa.Column('staff', sa.String(length=120), nullable=True),
    sa.Column('needs_ack', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['itin_case_id'], ['itin_case_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itin_price_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itin_price_quotes_itin_case_id'), ['itin_case_id'], unique=False)

    with op.batch_alter_table('itin_case_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_status', sa.String(length=12), server_default='none', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itin_case_data', schema=None) as batch_op:
        batch_op.drop_column('price_status')

    with op.batch_alter_table('itin_price_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itin_price_quotes_itin_case_id'))

    op.drop_table('itin_price_quotes')
    op.drop_table('itin_price_rules')
    # ### end Alembic commands ###
