"""add page builder html/css columns

Revision ID: 1385bfa78a33
Revises: e77b1db0b8cb
Create Date: 2026-09-03 18:15:30.551770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1385bfa78a33'
down_revision = 'e77b1db0b8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('builder_html_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('builder_css_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('builder_html_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('builder_css_es', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('builder_css_es')
        batch_op.drop_column('builder_html_es')
        batch_op.drop_column('builder_css_en')
        batch_op.drop_column('builder_html_en')

    # ### end Alembic commands ###
