"""add case simulation module for OG Forensic Training

Revision ID: 15da5e60cae2
Revises: fa09b2871c4c
Create Date: 2026-09-08 11:28:03.016424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15da5e60cae2'
down_revision = 'fa09b2871c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_es', sa.String(length=200), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_es', sa.Text(), nullable=True),
    sa.Column('client_profile_en', sa.Text(), nullable=True),
    sa.Column('client_profile_es', sa.Text(), nullable=True),
    sa.Column('instructions_en', sa.Text(), nullable=True),
    sa.Column('instructions_es', sa.Text(), nullable=True),
    sa.Column('passing_score', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id')
    )
    op.create_table('case_simulation_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_simulation_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['case_simulation_id'], ['case_simulations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_simulation_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_simulation_id', sa.Integer(), nullable=False),
    sa.Column('label_en', sa.String(length=200), nullable=False),
    sa.Column('label_es', sa.String(length=200), nullable=False),
    sa.Column('doc_type', sa.String(length=60), nullable=True),
    sa.Column('file_filename', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_simulation_id'], ['case_simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_simulation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_simulation_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('prompt_en', sa.Text(), nullable=False),
    sa.Column('prompt_es', sa.Text(), nullable=False),
    sa.Column('explanation_en', sa.Text(), nullable=True),
    sa.Column('explanation_es', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('requires_justification', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expected_response_en', sa.Text(), nullable=True),
    sa.Column('expected_response_es', sa.Text(), nullable=True),
    sa.Column('rubric_notes_en', sa.Text(), nullable=True),
    sa.Column('rubric_notes_es', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_simulation_id'], ['case_simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_simulation_task_accepted_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('answer_en', sa.String(length=300), nullable=False),
    sa.Column('answer_es', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['case_simulation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_simulation_task_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('text_en', sa.String(length=300), nullable=False),
    sa.Column('text_es', sa.String(length=300), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['case_simulation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_simulation_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('justification_text', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('ai_feedback_en', sa.Text(), nullable=True),
    sa.Column('ai_feedback_es', sa.Text(), nullable=True),
    sa.Column('reviewed_by_ai', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['case_simulation_attempts.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['case_simulation_task_options.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['case_simulation_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_simulation_response_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['case_simulation_task_options.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['case_simulation_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_simulation_response_options')
    op.drop_table('case_simulation_responses')
    op.drop_table('case_simulation_task_options')
    op.drop_table('case_simulation_task_accepted_answers')
    op.drop_table('case_simulation_tasks')
    op.drop_table('case_simulation_documents')
    op.drop_table('case_simulation_attempts')
    op.drop_table('case_simulations')
    # ### end Alembic commands ###
