"""Pages and menu system

Revision ID: 1df5688cc726
Revises: c6dfcaf6958e
Create Date: 2026-09-03 13:47:34.999997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df5688cc726'
down_revision = 'c6dfcaf6958e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_es', sa.String(length=200), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('content_es', sa.Text(), nullable=True),
    sa.Column('seo_title_en', sa.String(length=200), nullable=True),
    sa.Column('seo_title_es', sa.String(length=200), nullable=True),
    sa.Column('seo_description_en', sa.String(length=300), nullable=True),
    sa.Column('seo_description_es', sa.String(length=300), nullable=True),
    sa.Column('parent_page_id', sa.Integer(), nullable=True),
    sa.Column('parent_section', sa.String(length=30), nullable=True),
    sa.Column('show_in_menu', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    # ### end Alembic commands ###
