"""context key and help where

Revision ID: 2a00ebffff38
Revises: 6c03153d28a0
Create Date: 2026-09-18 18:34:20.487165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a00ebffff38'
down_revision = '6c03153d28a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('help_where_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('help_where_es', sa.Text(), nullable=True))

    with op.batch_alter_table('form_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_key', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_pages', schema=None) as batch_op:
        batch_op.drop_column('context_key')

    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.drop_column('help_where_es')
        batch_op.drop_column('help_where_en')

    # ### end Alembic commands ###
