"""widen truncated Smart Intake label/source_ref columns to Text

Revision ID: 363aeea03c7f
Revises: f1a9c02de7b4
Create Date: 2026-09-23 12:52:50.377191

Fixes a production-startup blocker: SQLite never enforces VARCHAR(N) length
(it is untyped/dynamic), so several seeder-authored values that were always
longer than their declared VARCHAR bound went unnoticed in development, then
failed the very first PostgreSQL startup with
`psycopg2.errors.StringDataRightTruncation` on an INSERT INTO form_fields.

An audit (seed the full startup pipeline into a fresh SQLite DB, then check
every String-typed column's actual inserted values against its declared max
length) found exactly six violating columns, all for the same underlying
reason: a column meant for short text is, for a handful of source forms,
holding the full verbatim official question/option/citation text instead
(DS-260's Security & Background section has no short Part/Item citation
scheme; several I-751/I-485/DS-260 certification checkboxes use a full
attestation sentence as their one option's label). These are not values a
seeder can reasonably be shortened to fit a bound without altering the
content OG asks customers to read, so the columns become Text (unbounded)
rather than a larger but still-arbitrary VARCHAR that the next form could
just as easily outgrow again:

  - form_fields.label_en / label_es           VARCHAR(300) -> Text
  - form_fields.source_ref                     VARCHAR(120) -> Text
  - form_field_options.label_en / label_es     VARCHAR(200) -> Text
  - ds260_sources.source_label                 VARCHAR(200) -> Text

`form_fields.placeholder_en/es` and `validation_message_en/es` (also
VARCHAR(300)) were audited too and had zero violations -- left untouched.
Postgres treats VARCHAR(n) and TEXT identically in storage/performance (a
VARCHAR(n) column is TEXT plus a length check), so this is a safe, purely
additive widening with no behavior change for any value that already fit.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363aeea03c7f'
down_revision = 'f1a9c02de7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds260_sources', schema=None) as batch_op:
        batch_op.alter_column('source_label',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('form_field_options', schema=None) as batch_op:
        batch_op.alter_column('label_en',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('label_es',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.alter_column('label_en',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('label_es',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('source_ref',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.alter_column('source_ref',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('label_es',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('label_en',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    with op.batch_alter_table('form_field_options', schema=None) as batch_op:
        batch_op.alter_column('label_es',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('label_en',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('ds260_sources', schema=None) as batch_op:
        batch_op.alter_column('source_label',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
