"""add admin users table and system SEO settings

Revision ID: 3708a1580f90
Revises: 424c9ca4f98e
Create Date: 2026-09-04 14:49:21.113858

"""
import os
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3708a1580f90'
down_revision = '424c9ca4f98e'
branch_labels = None
depends_on = None


admin_users_table = sa.table(
    "admin_users",
    sa.column("id", sa.Integer),
    sa.column("name", sa.String),
    sa.column("email", sa.String),
    sa.column("password_hash", sa.String),
    sa.column("is_active", sa.Boolean),
    sa.column("created_at", sa.DateTime),
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ga_measurement_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('search_console_verification', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('block_search_indexing', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###

    # Data migration: seed the first admin account from the existing .env
    # credentials, so the current login keeps working transparently once
    # admin auth moves from a single hardcoded pair to a real table.
    email = os.environ.get("ADMIN_EMAIL", "").strip()
    password_hash = os.environ.get("ADMIN_PASSWORD_HASH", "").strip()
    if email and password_hash:
        op.execute(
            admin_users_table.insert().values(
                name="Admin",
                email=email,
                password_hash=password_hash,
                is_active=True,
                created_at=datetime.utcnow(),
            )
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('block_search_indexing')
        batch_op.drop_column('search_console_verification')
        batch_op.drop_column('ga_measurement_id')

    op.drop_table('admin_users')
    # ### end Alembic commands ###
