"""add required_count to civics_questions

Revision ID: 3b5b4dc09d89
Revises: c8534b965f40
Create Date: 2026-09-07 09:01:51.467431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b5b4dc09d89'
down_revision = 'c8534b965f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('civics_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('civics_questions', schema=None) as batch_op:
        batch_op.drop_column('required_count')

    # ### end Alembic commands ###
