"""Lesson progress, quizzes, and certificates

Revision ID: 47deb24898a9
Revises: 1936e35320e6
Create Date: 2026-09-03 13:03:50.116253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47deb24898a9'
down_revision = '1936e35320e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_student_course_cert')
    )
    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uq_student_lesson')
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('score_percent', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('question_en', sa.Text(), nullable=False),
    sa.Column('question_es', sa.Text(), nullable=False),
    sa.Column('option_a_en', sa.String(length=300), nullable=False),
    sa.Column('option_a_es', sa.String(length=300), nullable=False),
    sa.Column('option_b_en', sa.String(length=300), nullable=False),
    sa.Column('option_b_es', sa.String(length=300), nullable=False),
    sa.Column('option_c_en', sa.String(length=300), nullable=False),
    sa.Column('option_c_es', sa.String(length=300), nullable=False),
    sa.Column('option_d_en', sa.String(length=300), nullable=False),
    sa.Column('option_d_es', sa.String(length=300), nullable=False),
    sa.Column('correct_option', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_passing_percentage', sa.Integer(), nullable=False, server_default='70'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('quiz_passing_percentage')

    op.drop_table('quiz_questions')
    op.drop_table('quiz_attempts')
    op.drop_table('lesson_progress')
    op.drop_table('certificates')
    # ### end Alembic commands ###
