"""service category list headings

Revision ID: 4aa2e4a05fe2
Revises: 6f3fd70909b0
Create Date: 2026-09-18 12:32:59.302773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa2e4a05fe2'
down_revision = '6f3fd70909b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist_title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('checklist_title_es', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('features_title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('features_title_es', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('included_title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('included_title_es', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_categories', schema=None) as batch_op:
        batch_op.drop_column('included_title_es')
        batch_op.drop_column('included_title_en')
        batch_op.drop_column('features_title_es')
        batch_op.drop_column('features_title_en')
        batch_op.drop_column('checklist_title_es')
        batch_op.drop_column('checklist_title_en')

    # ### end Alembic commands ###
