"""smart intake: form type, submission owner/service/current page

Revision ID: 54396c0d2586
Revises: 4aa2e4a05fe2
Create Date: 2026-09-18 12:38:12.874681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54396c0d2586'
down_revision = '4aa2e4a05fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_page', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_form_submissions_student', 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key('fk_form_submissions_service', 'services', ['service_id'], ['id'])

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_type', sa.String(length=20), server_default='inquiry', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_column('form_type')

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_form_submissions_service', type_='foreignkey')
        batch_op.drop_constraint('fk_form_submissions_student', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('current_page')
        batch_op.drop_column('service_id')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
