"""add_branding_asset_fields_to_site_settings

Revision ID: 561354a2ee0c
Revises: f317e65e97fa
Create Date: 2026-09-26 16:50:13.251115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561354a2ee0c'
down_revision = 'f317e65e97fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_logo_media_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('favicon_media_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('email_logo_media_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('social_logo_media_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_site_settings_admin_logo_media_id', 'media_assets', ['admin_logo_media_id'], ['id'])
        batch_op.create_foreign_key('fk_site_settings_email_logo_media_id', 'media_assets', ['email_logo_media_id'], ['id'])
        batch_op.create_foreign_key('fk_site_settings_favicon_media_id', 'media_assets', ['favicon_media_id'], ['id'])
        batch_op.create_foreign_key('fk_site_settings_social_logo_media_id', 'media_assets', ['social_logo_media_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_site_settings_social_logo_media_id', type_='foreignkey')
        batch_op.drop_constraint('fk_site_settings_favicon_media_id', type_='foreignkey')
        batch_op.drop_constraint('fk_site_settings_email_logo_media_id', type_='foreignkey')
        batch_op.drop_constraint('fk_site_settings_admin_logo_media_id', type_='foreignkey')
        batch_op.drop_column('social_logo_media_id')
        batch_op.drop_column('email_logo_media_id')
        batch_op.drop_column('favicon_media_id')
        batch_op.drop_column('admin_logo_media_id')

    # ### end Alembic commands ###
