"""CaseRevision (Tax/DL reopen change tracking)

Revision ID: 645dc3b27359
Revises: 2f79b0180827
Create Date: 2026-09-22 10:34:52.441999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645dc3b27359'
down_revision = '2f79b0180827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('reopened_at', sa.DateTime(), nullable=True),
    sa.Column('reopened_by', sa.String(length=10), server_default='admin', nullable=False),
    sa.Column('reopened_by_id', sa.Integer(), nullable=True),
    sa.Column('reopen_message', sa.Text(), nullable=True),
    sa.Column('resubmitted_at', sa.DateTime(), nullable=True),
    sa.Column('changes_json', sa.Text(), nullable=True),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('case_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_revisions_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_revisions_case_id'))

    op.drop_table('case_revisions')
    # ### end Alembic commands ###
