"""phase 3 reopen submissions revisions record fields

Revision ID: 68bc34892ba3
Revises: 86e358981c99
Create Date: 2026-09-18 17:24:58.641956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68bc34892ba3'
down_revision = '86e358981c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('reopened_at', sa.DateTime(), nullable=True),
    sa.Column('resubmitted_at', sa.DateTime(), nullable=True),
    sa.Column('changes_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_json', sa.Text(), nullable=True))

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reopened_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reopen_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('resubmitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reopen_count', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('features_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_column('features_json')

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_column('reopen_count')
        batch_op.drop_column('resubmitted_at')
        batch_op.drop_column('reopen_message')
        batch_op.drop_column('reopened_at')

    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.drop_column('config_json')

    op.drop_table('submission_revisions')
    # ### end Alembic commands ###
