"""OG Forms Builder: bilingual multi-page form engine

Revision ID: 6a6a1dce6816
Revises: 8c60be249da3
Create Date: 2026-09-18 10:05:12.160089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6a1dce6816'
down_revision = '8c60be249da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name_admin', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_es', sa.String(length=200), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_es', sa.Text(), nullable=True),
    sa.Column('submit_label_en', sa.String(length=80), server_default='Submit', nullable=False),
    sa.Column('submit_label_es', sa.String(length=80), server_default='Enviar', nullable=False),
    sa.Column('success_action', sa.String(length=20), server_default='message', nullable=False),
    sa.Column('success_message_en', sa.Text(), nullable=True),
    sa.Column('success_message_es', sa.Text(), nullable=True),
    sa.Column('redirect_url', sa.String(length=500), nullable=True),
    sa.Column('notify_admin_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notify_admin_emails', sa.String(length=500), nullable=True),
    sa.Column('notify_client_enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('confirmation_subject_en', sa.String(length=200), nullable=True),
    sa.Column('confirmation_subject_es', sa.String(length=200), nullable=True),
    sa.Column('confirmation_body_en', sa.Text(), nullable=True),
    sa.Column('confirmation_body_es', sa.Text(), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('button_style', sa.String(length=20), server_default='solid', nullable=False),
    sa.Column('border_radius', sa.String(length=20), server_default='rounded', nullable=False),
    sa.Column('spacing', sa.String(length=20), server_default='comfortable', nullable=False),
    sa.Column('background_style', sa.String(length=20), server_default='card', nullable=False),
    sa.Column('show_progress', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('form_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('title_es', sa.String(length=200), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_es', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='new', nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('display_email', sa.String(length=255), nullable=True),
    sa.Column('display_phone', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('field_type', sa.String(length=30), nullable=False),
    sa.Column('internal_name', sa.String(length=100), nullable=False),
    sa.Column('label_en', sa.String(length=300), nullable=True),
    sa.Column('label_es', sa.String(length=300), nullable=True),
    sa.Column('placeholder_en', sa.String(length=300), nullable=True),
    sa.Column('placeholder_es', sa.String(length=300), nullable=True),
    sa.Column('help_text_en', sa.Text(), nullable=True),
    sa.Column('help_text_es', sa.Text(), nullable=True),
    sa.Column('validation_message_en', sa.String(length=300), nullable=True),
    sa.Column('validation_message_es', sa.String(length=300), nullable=True),
    sa.Column('required', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('width', sa.String(length=10), server_default='full', nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('allowed_file_types', sa.String(length=200), nullable=True),
    sa.Column('max_file_size_mb', sa.Integer(), server_default='10', nullable=True),
    sa.Column('max_files', sa.Integer(), server_default='1', nullable=True),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('content_es', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('price_amount', sa.Float(), nullable=True),
    sa.Column('price_currency', sa.String(length=10), server_default='USD', nullable=True),
    sa.Column('service_source', sa.String(length=20), server_default='og_services', nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['form_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submission_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_conditional_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=10), server_default='all', nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('target_field_id', sa.Integer(), nullable=True),
    sa.Column('target_page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['target_field_id'], ['form_fields.id'], ),
    sa.ForeignKeyConstraint(['target_page_id'], ['form_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_field_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.Column('label_en', sa.String(length=200), nullable=False),
    sa.Column('label_es', sa.String(length=200), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submission_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_submission_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('field_label_snapshot', sa.String(length=300), nullable=False),
    sa.Column('field_internal_name', sa.String(length=100), nullable=False),
    sa.Column('field_type_snapshot', sa.String(length=30), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_rule_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=20), server_default='equals', nullable=False),
    sa.Column('value', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['form_fields.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['form_conditional_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_rule_conditions')
    op.drop_table('form_submission_values')
    op.drop_table('form_submission_files')
    op.drop_table('form_field_options')
    op.drop_table('form_conditional_rules')
    op.drop_table('form_submission_notes')
    op.drop_table('form_fields')
    op.drop_table('form_submissions')
    op.drop_table('form_pages')
    op.drop_table('forms')
    # ### end Alembic commands ###
