"""form pages group key

Revision ID: 6c03153d28a0
Revises: 68bc34892ba3
Create Date: 2026-09-18 17:40:20.598789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c03153d28a0'
down_revision = '68bc34892ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_key', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_pages', schema=None) as batch_op:
        batch_op.drop_column('group_key')

    # ### end Alembic commands ###
