"""drop unused page builder columns

Revision ID: 6e81da889b2b
Revises: 1385bfa78a33
Create Date: 2026-09-03 18:39:52.187697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e81da889b2b'
down_revision = '1385bfa78a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('builder_html_en')
        batch_op.drop_column('builder_html_es')
        batch_op.drop_column('builder_css_en')
        batch_op.drop_column('builder_css_es')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('builder_css_es', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('builder_css_en', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('builder_html_es', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('builder_html_en', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
