"""site content: media library, service categories, services

Revision ID: 6f3fd70909b0
Revises: a1c0de5e0001
Create Date: 2026-09-18 12:13:11.744913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f3fd70909b0'
down_revision = 'a1c0de5e0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stored_path', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('alt_en', sa.String(length=300), nullable=True),
    sa.Column('alt_es', sa.String(length=300), nullable=True),
    sa.Column('tag', sa.String(length=60), nullable=True),
    sa.Column('mime_type', sa.String(length=60), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_path')
    )
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('endpoint', sa.String(length=80), nullable=False),
    sa.Column('subpage_endpoint', sa.String(length=80), nullable=True),
    sa.Column('icon', sa.String(length=30), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('show_in_nav', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_es', sa.String(length=200), nullable=False),
    sa.Column('short_en', sa.String(length=300), nullable=True),
    sa.Column('short_es', sa.String(length=300), nullable=True),
    sa.Column('hero_badge_en', sa.String(length=120), nullable=True),
    sa.Column('hero_badge_es', sa.String(length=120), nullable=True),
    sa.Column('hero_title_en', sa.String(length=200), nullable=True),
    sa.Column('hero_title_es', sa.String(length=200), nullable=True),
    sa.Column('hero_text_en', sa.Text(), nullable=True),
    sa.Column('hero_text_es', sa.Text(), nullable=True),
    sa.Column('intro_title_en', sa.String(length=200), nullable=True),
    sa.Column('intro_title_es', sa.String(length=200), nullable=True),
    sa.Column('intro_body_en', sa.Text(), nullable=True),
    sa.Column('intro_body_es', sa.Text(), nullable=True),
    sa.Column('contact_note_en', sa.Text(), nullable=True),
    sa.Column('contact_note_es', sa.Text(), nullable=True),
    sa.Column('info_title_en', sa.String(length=200), nullable=True),
    sa.Column('info_title_es', sa.String(length=200), nullable=True),
    sa.Column('info_body_en', sa.Text(), nullable=True),
    sa.Column('info_body_es', sa.Text(), nullable=True),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('content_es', sa.Text(), nullable=True),
    sa.Column('disclaimer_en', sa.Text(), nullable=True),
    sa.Column('disclaimer_es', sa.Text(), nullable=True),
    sa.Column('final_cta_title_en', sa.String(length=200), nullable=True),
    sa.Column('final_cta_title_es', sa.String(length=200), nullable=True),
    sa.Column('final_cta_body_en', sa.Text(), nullable=True),
    sa.Column('final_cta_body_es', sa.Text(), nullable=True),
    sa.Column('cta_label_en', sa.String(length=120), nullable=True),
    sa.Column('cta_label_es', sa.String(length=120), nullable=True),
    sa.Column('cta_mode', sa.String(length=20), server_default='default', nullable=False),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('whatsapp_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('seo_title_en', sa.String(length=200), nullable=True),
    sa.Column('seo_title_es', sa.String(length=200), nullable=True),
    sa.Column('seo_description_en', sa.String(length=300), nullable=True),
    sa.Column('seo_description_es', sa.String(length=300), nullable=True),
    sa.Column('hero_image_id', sa.Integer(), nullable=True),
    sa.Column('hero_mobile_image_id', sa.Integer(), nullable=True),
    sa.Column('card_image_id', sa.Integer(), nullable=True),
    sa.Column('overview_image_id', sa.Integer(), nullable=True),
    sa.Column('social_image_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('hero_focus', sa.String(length=10), server_default='center', nullable=False),
    sa.Column('card_focus', sa.String(length=10), server_default='center', nullable=False),
    sa.ForeignKeyConstraint(['card_image_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['hero_image_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['hero_mobile_image_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['overview_image_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['social_image_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('admin_name', sa.String(length=200), nullable=True),
    sa.Column('icon', sa.String(length=30), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('badge_en', sa.String(length=40), nullable=True),
    sa.Column('badge_es', sa.String(length=40), nullable=True),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_es', sa.String(length=200), nullable=False),
    sa.Column('short_en', sa.String(length=300), nullable=True),
    sa.Column('short_es', sa.String(length=300), nullable=True),
    sa.Column('hero_text_en', sa.Text(), nullable=True),
    sa.Column('hero_text_es', sa.Text(), nullable=True),
    sa.Column('content_title_en', sa.String(length=200), nullable=True),
    sa.Column('content_title_es', sa.String(length=200), nullable=True),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('content_es', sa.Text(), nullable=True),
    sa.Column('disclaimer_en', sa.Text(), nullable=True),
    sa.Column('disclaimer_es', sa.Text(), nullable=True),
    sa.Column('cta_label_en', sa.String(length=120), nullable=True),
    sa.Column('cta_label_es', sa.String(length=120), nullable=True),
    sa.Column('cta_mode', sa.String(length=20), server_default='default', nullable=False),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('whatsapp_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('requires_intake', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('requires_account', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('nj_in_person', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('tx_in_person', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('remote_nationwide', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('scope_note_en', sa.Text(), nullable=True),
    sa.Column('scope_note_es', sa.Text(), nullable=True),
    sa.Column('seo_title_en', sa.String(length=200), nullable=True),
    sa.Column('seo_title_es', sa.String(length=200), nullable=True),
    sa.Column('seo_description_en', sa.String(length=300), nullable=True),
    sa.Column('seo_description_es', sa.String(length=300), nullable=True),
    sa.Column('hero_image_id', sa.Integer(), nullable=True),
    sa.Column('hero_mobile_image_id', sa.Integer(), nullable=True),
    sa.Column('card_image_id', sa.Integer(), nullable=True),
    sa.Column('overview_image_id', sa.Integer(), nullable=True),
    sa.Column('social_image_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('hero_focus', sa.String(length=10), server_default='center', nullable=False),
    sa.Column('card_focus', sa.String(length=10), server_default='center', nullable=False),
    sa.ForeignKeyConstraint(['card_image_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['hero_image_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['hero_mobile_image_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['overview_image_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['social_image_id'], ['media_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'slug', name='uq_service_category_slug')
    )
    op.create_table('service_content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=False),
    sa.Column('title_es', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=True),
    sa.Column('body_es', sa.Text(), nullable=True),
    sa.CheckConstraint('(service_id IS NOT NULL AND category_id IS NULL) OR (service_id IS NULL AND category_id IS NOT NULL)', name='ck_content_item_one_owner'),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_related',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('related_service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['related_service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('service_id', 'related_service_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_related')
    op.drop_table('service_content_items')
    op.drop_table('services')
    op.drop_table('service_categories')
    op.drop_table('media_assets')
    # ### end Alembic commands ###
