"""add site settings table

Revision ID: 72d93b2f8aca
Revises: 6e81da889b2b
Create Date: 2026-09-03 19:22:08.067851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d93b2f8aca'
down_revision = '6e81da889b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facebook_url', sa.String(length=300), nullable=True),
    sa.Column('instagram_url', sa.String(length=300), nullable=True),
    sa.Column('tiktok_url', sa.String(length=300), nullable=True),
    sa.Column('youtube_url', sa.String(length=300), nullable=True),
    sa.Column('linkedin_url', sa.String(length=300), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_settings')
    # ### end Alembic commands ###
