"""form submission resume token and completion flag

Revision ID: 7dc5e57be2ff
Revises: 6a6a1dce6816
Create Date: 2026-09-18 10:12:27.294068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc5e57be2ff'
down_revision = '6a6a1dce6816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_token', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('is_complete', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_unique_constraint('uq_form_submissions_resume_token', ['resume_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_form_submissions_resume_token', type_='unique')
        batch_op.drop_column('is_complete')
        batch_op.drop_column('resume_token')

    # ### end Alembic commands ###
