"""add certificate file_filename

Revision ID: 842a9534853a
Revises: c0d5ef5d4a48
Create Date: 2026-09-16 13:09:57.565067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842a9534853a'
down_revision = 'c0d5ef5d4a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('file_filename')

    # ### end Alembic commands ###
