"""smart intake phase 2: versioning, activity, customer profile

Revision ID: 86e358981c99
Revises: 050e9258588f
Create Date: 2026-09-18 13:45:59.525636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e358981c99'
down_revision = '050e9258588f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index('ix_activity_customer_created', ['customer_id', 'created_at'], unique=False)

    op.create_table('customer_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=120), nullable=True),
    sa.Column('author_admin_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_ref', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('source_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_sensitive', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('pattern', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('date_rule', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('help_detail_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('help_detail_es', sa.Text(), nullable=True))

    with op.batch_alter_table('form_submission_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('form_submission_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('is_customer_visible', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('source_edition_snapshot', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('snapshot_json', sa.Text(), nullable=True))

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_form_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('source_edition', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('previous_version_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_forms_previous_version', 'forms', ['previous_version_id'], ['id'])

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intake_label', sa.String(length=120), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('preferred_language')
        batch_op.drop_column('phone')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('intake_label')

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_forms_previous_version', type_='foreignkey')
        batch_op.drop_column('previous_version_id')
        batch_op.drop_column('published_at')
        batch_op.drop_column('version')
        batch_op.drop_column('source_edition')
        batch_op.drop_column('source_form_name')

    with op.batch_alter_table('form_submissions', schema=None) as batch_op:
        batch_op.drop_column('snapshot_json')
        batch_op.drop_column('source_edition_snapshot')
        batch_op.drop_column('form_version')

    with op.batch_alter_table('form_submission_notes', schema=None) as batch_op:
        batch_op.drop_column('is_customer_visible')
        batch_op.drop_column('author_name')

    with op.batch_alter_table('form_submission_files', schema=None) as batch_op:
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('mime_type')

    with op.batch_alter_table('form_fields', schema=None) as batch_op:
        batch_op.drop_column('help_detail_es')
        batch_op.drop_column('help_detail_en')
        batch_op.drop_column('date_rule')
        batch_op.drop_column('pattern')
        batch_op.drop_column('is_sensitive')
        batch_op.drop_column('source_note')
        batch_op.drop_column('source_ref')

    op.drop_table('customer_notes')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_customer_created')

    op.drop_table('activity_events')
    # ### end Alembic commands ###
