"""course-level certificate settings and revoke status

Revision ID: 8c60be249da3
Revises: c855ed14797e
Create Date: 2026-09-17 22:20:15.890452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c60be249da3'
down_revision = 'c855ed14797e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='valid', nullable=False))
        batch_op.add_column(sa.Column('revoked_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_enabled', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('certificate_trigger', sa.String(length=30), server_default='course_completion', nullable=False))
        batch_op.add_column(sa.Column('certificate_template', sa.String(length=20), server_default='classic', nullable=False))
        batch_op.add_column(sa.Column('certificate_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('certificate_issuer_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('certificate_issuer_subtitle', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('certificate_signatory_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('certificate_signatory_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('certificate_signature_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('certificate_logo_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('certificate_show_qr', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('certificate_show_id', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('certificate_show_id')
        batch_op.drop_column('certificate_show_qr')
        batch_op.drop_column('certificate_logo_image')
        batch_op.drop_column('certificate_signature_image')
        batch_op.drop_column('certificate_signatory_title')
        batch_op.drop_column('certificate_signatory_name')
        batch_op.drop_column('certificate_issuer_subtitle')
        batch_op.drop_column('certificate_issuer_name')
        batch_op.drop_column('certificate_title')
        batch_op.drop_column('certificate_template')
        batch_op.drop_column('certificate_trigger')
        batch_op.drop_column('certificate_enabled')

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_column('revoked_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
