"""add custom forms and inquiry extra_data

Revision ID: 9ea73d556a02
Revises: 72d93b2f8aca
Create Date: 2026-09-03 20:02:16.893875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea73d556a02'
down_revision = '72d93b2f8aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name_admin', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('title_es', sa.String(length=200), nullable=False),
    sa.Column('intro_en', sa.Text(), nullable=True),
    sa.Column('intro_es', sa.Text(), nullable=True),
    sa.Column('submit_label_en', sa.String(length=80), nullable=False),
    sa.Column('submit_label_es', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('custom_form_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('label_en', sa.String(length=200), nullable=False),
    sa.Column('label_es', sa.String(length=200), nullable=False),
    sa.Column('placeholder_en', sa.String(length=200), nullable=True),
    sa.Column('placeholder_es', sa.String(length=200), nullable=True),
    sa.Column('options_en', sa.Text(), nullable=True),
    sa.Column('options_es', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['custom_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('extra_data', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_inquiries_form_id', 'custom_forms', ['form_id'], ['id'])

    with op.batch_alter_table('page_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_form_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_page_sections_custom_form_id', 'custom_forms', ['custom_form_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_sections', schema=None) as batch_op:
        batch_op.drop_constraint('fk_page_sections_custom_form_id', type_='foreignkey')
        batch_op.drop_column('custom_form_id')

    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inquiries_form_id', type_='foreignkey')
        batch_op.drop_column('extra_data')
        batch_op.drop_column('form_id')

    op.drop_table('custom_form_fields')
    op.drop_table('custom_forms')
    # ### end Alembic commands ###
