"""NJ Driver License service + Knowledge Test practice

Revision ID: a22a485fadfe
Revises: acc1d0e5e001
Create Date: 2026-09-22 00:02:24.494770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22a485fadfe'
down_revision = 'acc1d0e5e001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dl_price_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=14), nullable=False),
    sa.Column('doc_key', sa.String(length=40), nullable=True),
    sa.Column('lang_key', sa.String(length=10), nullable=True),
    sa.Column('label_en', sa.String(length=160), nullable=False),
    sa.Column('label_es', sa.String(length=160), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_dl_price_rule')
    )
    op.create_table('dl_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_key', sa.String(length=60), nullable=False),
    sa.Column('topic', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.String(length=10), server_default='medium', nullable=False),
    sa.Column('question_en', sa.Text(), nullable=False),
    sa.Column('question_es', sa.Text(), nullable=False),
    sa.Column('explanation_en', sa.Text(), nullable=True),
    sa.Column('explanation_es', sa.Text(), nullable=True),
    sa.Column('source_ref', sa.String(length=200), nullable=True),
    sa.Column('version', sa.String(length=20), server_default='v1', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_key')
    )
    op.create_table('mvc_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('appointment_types_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('dl_question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text_en', sa.String(length=300), nullable=False),
    sa.Column('text_es', sa.String(length=300), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['dl_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dl_case_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('doc_choices_json', sa.Text(), nullable=True),
    sa.Column('current_step', sa.String(length=40), nullable=True),
    sa.Column('milestone', sa.String(length=20), server_default='documents', nullable=False),
    sa.Column('initial_permit_state', sa.String(length=20), server_default='not_started', nullable=False),
    sa.Column('knowledge_test_state', sa.String(length=20), server_default='not_started', nullable=False),
    sa.Column('road_test_state', sa.String(length=20), server_default='to_be_determined', nullable=False),
    sa.Column('appointment_json', sa.Text(), nullable=True),
    sa.Column('rules_version', sa.String(length=20), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(), nullable=True),
    sa.Column('reopen_message', sa.Text(), nullable=True),
    sa.Column('resubmit_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('terms_id', sa.Integer(), nullable=True),
    sa.Column('customer_message', sa.Text(), nullable=True),
    sa.Column('price_status', sa.String(length=12), server_default='none', nullable=False),
    sa.Column('loc1_id', sa.Integer(), nullable=True),
    sa.Column('loc2_id', sa.Integer(), nullable=True),
    sa.Column('loc3_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['loc1_id'], ['mvc_locations.id'], ),
    sa.ForeignKeyConstraint(['loc2_id'], ['mvc_locations.id'], ),
    sa.ForeignKeyConstraint(['loc3_id'], ['mvc_locations.id'], ),
    sa.ForeignKeyConstraint(['terms_id'], ['terms_acceptances.id'], name='fk_dl_terms'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('dl_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('dl_case_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('topic_filter', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=2), server_default='en', nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=True),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dl_case_id'], ['dl_case_data.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dl_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dl_attempts_student_id'), ['student_id'], unique=False)

    op.create_table('dl_price_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dl_case_id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('lines_json', sa.Text(), nullable=True),
    sa.Column('system_estimate_cents', sa.Integer(), nullable=True),
    sa.Column('has_review_item', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('final_total_cents', sa.Integer(), nullable=True),
    sa.Column('previous_total_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=400), nullable=True),
    sa.Column('staff', sa.String(length=120), nullable=True),
    sa.Column('needs_ack', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dl_case_id'], ['dl_case_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dl_price_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dl_price_quotes_dl_case_id'), ['dl_case_id'], unique=False)

    op.create_table('dl_attempt_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['dl_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['dl_questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['dl_question_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dl_attempt_responses')
    with op.batch_alter_table('dl_price_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dl_price_quotes_dl_case_id'))

    op.drop_table('dl_price_quotes')
    with op.batch_alter_table('dl_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dl_attempts_student_id'))

    op.drop_table('dl_attempts')
    op.drop_table('dl_case_data')
    op.drop_table('dl_question_options')
    op.drop_table('mvc_locations')
    op.drop_table('dl_questions')
    op.drop_table('dl_price_rules')
    # ### end Alembic commands ###
