"""charge_course_context

Revision ID: a5614f0aef99
Revises: 1486c9978526
Create Date: 2026-09-22 17:02:33.950968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5614f0aef99'
down_revision = '1486c9978526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_charges_course', 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.drop_constraint('fk_charges_course', type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
