"""i485 links and doc basis

Revision ID: a7972377f4aa
Revises: 0fb7ac30f97e
Create Date: 2026-09-18 23:03:09.081219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7972377f4aa'
down_revision = '0fb7ac30f97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_application_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('related_submission_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), server_default='underlying_petition', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['related_submission_id'], ['form_submissions.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'related_submission_id', 'kind', name='uq_app_link')
    )
    with op.batch_alter_table('case_application_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_case_application_links_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_application_links_related_submission_id'), ['related_submission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_application_links_submission_id'), ['submission_id'], unique=False)

    with op.batch_alter_table('case_document_requirements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reused_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('doc_basis', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_document_requirements', schema=None) as batch_op:
        batch_op.drop_column('doc_basis')
        batch_op.drop_column('reused_at')

    with op.batch_alter_table('case_application_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_application_links_submission_id'))
        batch_op.drop_index(batch_op.f('ix_case_application_links_related_submission_id'))
        batch_op.drop_index(batch_op.f('ix_case_application_links_case_id'))

    op.drop_table('case_application_links')
    # ### end Alembic commands ###
