"""add category to civics_questions

Revision ID: a9e8d52a4f2b
Revises: 3b5b4dc09d89
Create Date: 2026-09-07 09:20:03.697943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e8d52a4f2b'
down_revision = '3b5b4dc09d89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('civics_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('civics_questions', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
