"""widen quiz and case simulation option text columns to Text

Revision ID: b263d7c3e69e
Revises: 363aeea03c7f
Create Date: 2026-09-23 13:19:30.043185

Second and final fix for the same class of bug as 363aeea03c7f: a value from
the real content-migration package (content_migration/exports/20260923T173059Z)
exceeded a VARCHAR(300) bound, this time during `INSERT INTO
quiz_question_options` on the VPS's PostgreSQL. Prompted a full audit of
data.json directly (not a re-seed proxy) against every String(N) column of
every table the package touches (24 tables, 138 String(N) columns) -- not
just the one that failed. Found exactly one real violation:

  - quiz_question_options.text_es    VARCHAR(300) -> 306 chars (a NJ Notary
    exam answer option describing a specific notarial act)

quiz_question_options.text_en is widened alongside text_es for the same
reason label_en/es were both widened in 363aeea03c7f: a quiz answer choice
can by nature be a full sentence, and content on one but not the other side
of a bilingual pair is a matter of which language happened to run long in
which question, not a property special to _es.

case_simulation_task_options.text_en/es (0 violations in this specific
package) is widened alongside it: its own docstring already says it "plays
the same role" as quiz_question_options -- same bilingual option-choice
shape, same VARCHAR(300) bound, same real risk of a full-sentence answer
choice. Fixing the one that already broke while leaving its structural twin
at the same bound would just be waiting for the next Case Simulation lesson
to hit the identical wall.

Every other String(N) column across all 24 tables in the package (Academy,
Case Simulation, Pages, PageBlocks, Blog, SiteSettings, MediaAssets, and the
request-a-quote Form tree) was audited and found within its declared bound
-- see the 2026-09-23 full-package audit for the complete "0 violations"
confirmation.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b263d7c3e69e'
down_revision = '363aeea03c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case_simulation_task_options', schema=None) as batch_op:
        batch_op.alter_column('text_en',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('text_es',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('quiz_question_options', schema=None) as batch_op:
        batch_op.alter_column('text_en',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('text_es',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question_options', schema=None) as batch_op:
        batch_op.alter_column('text_es',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('text_en',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    with op.batch_alter_table('case_simulation_task_options', schema=None) as batch_op:
        batch_op.alter_column('text_es',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.alter_column('text_en',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###
