"""add multi-type quiz builder (question types, options, responses, attempt status)

Revision ID: c0d5ef5d4a48
Revises: fe212b58364b
Create Date: 2026-09-11 10:32:06.949118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0d5ef5d4a48'
down_revision = 'fe212b58364b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_question_accepted_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_en', sa.String(length=300), nullable=False),
    sa.Column('answer_es', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text_en', sa.String(length=300), nullable=True),
    sa.Column('text_es', sa.String(length=300), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('response_number', sa.Float(), nullable=True),
    sa.Column('file_filename', sa.String(length=255), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('reviewed_by_admin', sa.Boolean(), nullable=False),
    sa.Column('admin_feedback', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['quiz_question_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_response_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['quiz_question_options.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['quiz_responses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_max_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiz_allow_retry', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('quiz_show_results', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('quiz_show_correct_answers', sa.Boolean(), server_default='1', nullable=False))

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='graded', nullable=False))
        batch_op.add_column(sa.Column('score_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_score_points', sa.Integer(), nullable=True))
        batch_op.alter_column('passed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_type', sa.String(length=20), server_default='single_choice', nullable=False))
        batch_op.add_column(sa.Column('points', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('required', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('feedback_correct_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_correct_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_incorrect_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('feedback_incorrect_es', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('correct_number', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('number_tolerance', sa.Float(), server_default='0', nullable=False))
        batch_op.alter_column('option_a_en',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('option_a_es',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('option_b_en',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('option_b_es',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('option_c_en',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('option_c_es',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('option_d_en',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('option_d_es',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('correct_option',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.alter_column('correct_option',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
        batch_op.alter_column('option_d_es',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('option_d_en',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('option_c_es',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('option_c_en',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('option_b_es',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('option_b_en',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('option_a_es',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('option_a_en',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.drop_column('number_tolerance')
        batch_op.drop_column('correct_number')
        batch_op.drop_column('feedback_incorrect_es')
        batch_op.drop_column('feedback_incorrect_en')
        batch_op.drop_column('feedback_correct_es')
        batch_op.drop_column('feedback_correct_en')
        batch_op.drop_column('required')
        batch_op.drop_column('points')
        batch_op.drop_column('question_type')

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.alter_column('passed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('max_score_points')
        batch_op.drop_column('score_points')
        batch_op.drop_column('status')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('quiz_show_correct_answers')
        batch_op.drop_column('quiz_show_results')
        batch_op.drop_column('quiz_allow_retry')
        batch_op.drop_column('quiz_max_attempts')

    op.drop_table('quiz_response_options')
    op.drop_table('quiz_responses')
    op.drop_table('quiz_question_options')
    op.drop_table('quiz_question_accepted_answers')
    # ### end Alembic commands ###
