"""Admin Notification Center

Revision ID: c13c79ae437f
Revises: 0fdc959cb544
Create Date: 2026-09-25 01:07:47.999728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13c79ae437f'
down_revision = '0fdc959cb544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=50), nullable=False),
    sa.Column('admin_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_table('admin_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=50), nullable=False),
    sa.Column('group_key', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=150), nullable=True),
    sa.Column('admin_visible', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('email_attempted', sa.Boolean(), nullable=False),
    sa.Column('email_status', sa.String(length=20), nullable=True),
    sa.Column('email_recipient', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_notifications_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_notifications_event_key'), ['event_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_notifications_group_key'), ['group_key'], unique=False)

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_recipient_email', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('notification_recipient_email')

    with op.batch_alter_table('admin_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_notifications_group_key'))
        batch_op.drop_index(batch_op.f('ix_admin_notifications_event_key'))
        batch_op.drop_index(batch_op.f('ix_admin_notifications_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_admin_notifications_created_at'))

    op.drop_table('admin_notifications')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
