"""lms platform features: quiz kind, questions per page, course access duration, accent color, enrollment expiry

Revision ID: c855ed14797e
Revises: ce1c789250be
Create Date: 2026-09-17 20:36:59.221594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c855ed14797e'
down_revision = 'ce1c789250be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_duration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('accent_color', sa.String(length=7), nullable=True))

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_kind', sa.String(length=20), server_default='final', nullable=False))
        batch_op.add_column(sa.Column('quiz_questions_per_page', sa.Integer(), server_default='8', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('quiz_questions_per_page')
        batch_op.drop_column('quiz_kind')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('accent_color')
        batch_op.drop_column('access_duration_days')

    # ### end Alembic commands ###
