"""bilingual presentation slides

Revision ID: ce1c789250be
Revises: 842a9534853a
Create Date: 2026-09-16 15:27:41.937327

Renames the existing single-language slide columns to their English
equivalents (preserving any existing slide data as the English version, per
spec) and adds new nullable Spanish columns. Hand-edited from the
autogenerated drop+add to a safe rename — autogenerate cannot detect renames.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce1c789250be'
down_revision = '842a9534853a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('lesson_slides', schema=None) as batch_op:
        batch_op.alter_column('image_filename', new_column_name='image_en',
                               existing_type=sa.String(length=255), nullable=True)
        batch_op.alter_column('audio_filename', new_column_name='audio_en',
                               existing_type=sa.String(length=255), nullable=True)
        batch_op.add_column(sa.Column('image_es', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('audio_es', sa.String(length=255), nullable=True))


def downgrade():
    with op.batch_alter_table('lesson_slides', schema=None) as batch_op:
        batch_op.drop_column('audio_es')
        batch_op.drop_column('image_es')
        batch_op.alter_column('audio_en', new_column_name='audio_filename',
                               existing_type=sa.String(length=255), nullable=True)
        batch_op.alter_column('image_en', new_column_name='image_filename',
                               existing_type=sa.String(length=255), nullable=False)
