"""Add BlogPostView for first-party blog view tracking

Revision ID: d7be797e1928
Revises: 561354a2ee0c
Create Date: 2026-09-27 08:05:11.008743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7be797e1928'
down_revision = '561354a2ee0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_post_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_post_id', sa.Integer(), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_post_id', 'visitor_hash', name='uq_blog_post_view_post_visitor_day')
    )
    with op.batch_alter_table('blog_post_views', schema=None) as batch_op:
        batch_op.create_index('ix_blog_post_views_post_viewed_at', ['blog_post_id', 'viewed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post_views', schema=None) as batch_op:
        batch_op.drop_index('ix_blog_post_views_post_viewed_at')

    op.drop_table('blog_post_views')
    # ### end Alembic commands ###
