"""files_from_og_metadata_and_enrollment_access

Revision ID: db4a161092d7
Revises: 645dc3b27359
Create Date: 2026-09-22 13:19:01.484067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4a161092d7'
down_revision = '645dc3b27359'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=30), server_default='other', nullable=False))
        batch_op.add_column(sa.Column('related_service', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('tax_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('released_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_customer_files_released_by', 'admin_users', ['released_by_admin_id'], ['id'])
        batch_op.create_foreign_key('fk_customer_files_person', 'persons', ['person_id'], ['id'])

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_source', sa.String(length=30), server_default='paid_new_site', nullable=False))
        batch_op.add_column(sa.Column('granted_by_admin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('granted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('migration_reference', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('internal_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('revoked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('revoked_by_admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_enrollments_revoked_by', 'admin_users', ['revoked_by_admin_id'], ['id'])
        batch_op.create_foreign_key('fk_enrollments_granted_by', 'admin_users', ['granted_by_admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_enrollments_revoked_by', type_='foreignkey')
        batch_op.drop_constraint('fk_enrollments_granted_by', type_='foreignkey')
        batch_op.drop_column('revoked_by_admin_id')
        batch_op.drop_column('revoked_at')
        batch_op.drop_column('internal_note')
        batch_op.drop_column('migration_reference')
        batch_op.drop_column('granted_at')
        batch_op.drop_column('granted_by_admin_id')
        batch_op.drop_column('access_source')

    with op.batch_alter_table('customer_files', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customer_files_released_by', type_='foreignkey')
        batch_op.drop_constraint('fk_customer_files_person', type_='foreignkey')
        batch_op.drop_column('released_by_admin_id')
        batch_op.drop_column('tax_year')
        batch_op.drop_column('related_service')
        batch_op.drop_column('category')
        batch_op.drop_column('person_id')

    # ### end Alembic commands ###
