"""add page_sections table

Revision ID: e77b1db0b8cb
Revises: 0539ed7f29c0
Create Date: 2026-09-03 17:27:15.302912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77b1db0b8cb'
down_revision = '0539ed7f29c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=20), nullable=False),
    sa.Column('heading_en', sa.String(length=200), nullable=True),
    sa.Column('heading_es', sa.String(length=200), nullable=True),
    sa.Column('text_en', sa.Text(), nullable=True),
    sa.Column('text_es', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('button_label_en', sa.String(length=150), nullable=True),
    sa.Column('button_label_es', sa.String(length=150), nullable=True),
    sa.Column('link_page_id', sa.Integer(), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['link_page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_sections')
    # ### end Alembic commands ###
