"""Wix customer import and account invitations

Revision ID: f1dc1a0b5183
Revises: c13c79ae437f
Create Date: 2026-09-25 09:01:52.227974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1dc1a0b5183'
down_revision = 'c13c79ae437f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('raw_csv', sa.Text(), nullable=False),
    sa.Column('column_mapping_json', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('existing_count', sa.Integer(), nullable=False),
    sa.Column('invalid_count', sa.Integer(), nullable=False),
    sa.Column('missing_email_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('failed_reason', sa.String(length=300), nullable=True),
    sa.Column('invited_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['invited_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_invitations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_invitations_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_invitations_token_hash'), ['token_hash'], unique=False)

    op.create_table('import_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=300), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_rows_batch_id'), ['batch_id'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_activation', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('import_batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_students_import_batch_id', 'import_batches', ['import_batch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_import_batch_id', type_='foreignkey')
        batch_op.drop_column('import_batch_id')
        batch_op.drop_column('needs_activation')

    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_rows_batch_id'))

    op.drop_table('import_rows')
    with op.batch_alter_table('account_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_invitations_token_hash'))
        batch_op.drop_index(batch_op.f('ix_account_invitations_student_id'))
        batch_op.drop_index(batch_op.f('ix_account_invitations_status'))

    op.drop_table('account_invitations')
    op.drop_table('import_batches')
    # ### end Alembic commands ###
