"""Wix import: real CSV structure, address fields, validate/import split

Revision ID: f317e65e97fa
Revises: f1dc1a0b5183
Create Date: 2026-09-25 09:26:05.726025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f317e65e97fa'
down_revision = 'f1dc1a0b5183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        # server_default='0' is required here: staging already has an (empty/test) import_batches row,
        # and Postgres refuses a NOT NULL column added without a default when the table isn't empty.
        batch_op.add_column(sa.Column('ready_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('invalid_email_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('duplicate_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('validated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('invalid_count')

    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_street', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('address_state', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('address_zip', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_country', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('imported', sa.Boolean(), server_default='0', nullable=False))
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('full_name')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_street', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address_city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('address_state', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('address_zip', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address_country', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('address_country')
        batch_op.drop_column('address_zip')
        batch_op.drop_column('address_state')
        batch_op.drop_column('address_city')
        batch_op.drop_column('address_street')

    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('imported')
        batch_op.drop_column('address_country')
        batch_op.drop_column('address_zip')
        batch_op.drop_column('address_state')
        batch_op.drop_column('address_city')
        batch_op.drop_column('address_street')

    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invalid_count', sa.INTEGER(), nullable=False))
        batch_op.drop_column('validated_at')
        batch_op.drop_column('duplicate_count')
        batch_op.drop_column('invalid_email_count')
        batch_op.drop_column('ready_count')

    # ### end Alembic commands ###
