"""add officer profiles, interview scenarios, civics question flags, interview guardrail settings

Revision ID: fa09b2871c4c
Revises: a9e8d52a4f2b
Create Date: 2026-09-08 10:35:30.006070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa09b2871c4c'
down_revision = 'a9e8d52a4f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('avatar_filename', sa.String(length=255), nullable=True),
    sa.Column('voice', sa.String(length=20), nullable=False),
    sa.Column('languages', sa.String(length=20), nullable=False),
    sa.Column('tone_en', sa.Text(), nullable=True),
    sa.Column('tone_es', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('civics_question_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('flagged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['civics_questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'question_id', name='uq_student_question_flag')
    )
    op.create_table('interview_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('officer_profile_id', sa.Integer(), nullable=False),
    sa.Column('scenario_type', sa.String(length=30), nullable=False),
    sa.Column('max_questions', sa.Integer(), nullable=False),
    sa.Column('passing_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['officer_profile_id'], ['officer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id')
    )
    with op.batch_alter_table('civics_test_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_interactions_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('end_reason', sa.String(length=30), nullable=True))

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_max_duration_minutes', sa.Integer(), nullable=False, server_default='15'))
        batch_op.add_column(sa.Column('interview_max_ai_interactions', sa.Integer(), nullable=False, server_default='25'))
        batch_op.add_column(sa.Column('interview_max_daily_attempts', sa.Integer(), nullable=False, server_default='3'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('interview_max_daily_attempts')
        batch_op.drop_column('interview_max_ai_interactions')
        batch_op.drop_column('interview_max_duration_minutes')

    with op.batch_alter_table('civics_test_sessions', schema=None) as batch_op:
        batch_op.drop_column('end_reason')
        batch_op.drop_column('ai_interactions_count')

    op.drop_table('interview_scenarios')
    op.drop_table('civics_question_flags')
    op.drop_table('officer_profiles')
    # ### end Alembic commands ###
