"""add N-400 interview practice question bank and sessions

Revision ID: fe212b58364b
Revises: 15da5e60cae2
Create Date: 2026-09-11 09:20:50.913434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe212b58364b'
down_revision = '15da5e60cae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('n400_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('question_en', sa.Text(), nullable=False),
    sa.Column('question_es', sa.Text(), nullable=False),
    sa.Column('sample_answer_en', sa.Text(), nullable=True),
    sa.Column('sample_answer_es', sa.Text(), nullable=True),
    sa.Column('rubric_notes_en', sa.Text(), nullable=True),
    sa.Column('rubric_notes_es', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('n400_interview_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('ai_interactions_count', sa.Integer(), nullable=False),
    sa.Column('end_reason', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('n400_interview_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order_asked', sa.Integer(), nullable=False),
    sa.Column('student_answer_text', sa.Text(), nullable=True),
    sa.Column('ai_feedback_en', sa.Text(), nullable=True),
    sa.Column('ai_feedback_es', sa.Text(), nullable=True),
    sa.Column('reviewed_by_ai', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['n400_questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['n400_interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('n400_interview_answers')
    op.drop_table('n400_interview_sessions')
    op.drop_table('n400_questions')
    # ### end Alembic commands ###
